### ISSUE TITLE
heroku?

### ISSUE THREAD

**Issue by wulandrima1** [ngekoding/whatsapp-api-tutorial#1]
om ini bisa develop ke heroku ga?

**Comment by ngekoding** [comment]
Silahkan merujuk ke dua link berikut ini

- https://devcenter.heroku.com/articles/deploying-nodejs
- https://github.com/pedroslopez/whatsapp-web.js/issues/381

**Comment by vlogcod3r** [comment]
@ngekoding min mau tanya, saat setelah deploy ke heroku berhasil dan berjalan, bisa melakukan send message, bahkan setelah login barcode dan browser heroku app nya di tutup masih bisa merespon saat send message. tapi saat tidak digunakan lagi misal setelah 30 menit kemudia, app whatsapp web js yg di deploy di heroku tidak berjalan, send messagenya tidak berjalan.

saat di jalankan perinta heroku logs --tail errornya seperti ini:
![Screenshot 2022-08-04 064007](https://user-images.githubusercontent.com/78385926/182731027-27d01a7b-10a3-4dce-ac11-1ac82d465433.jpg)

whatsapp web js nya tidak pakai session, apa itu berpengaruh lalu bagaimana solusinya, karena bila ingin berjalan di heroku tidak dapat menggunakan file, dan legacy auth juga sudah tidak bisa di versi whatsapp yg sekarang.

terima kasih
