### ISSUE TITLE
Failed to load resource: the server responded with a status of 400 (Bad Request)

### ISSUE THREAD

**Issue by refanka-inv** [ngekoding/whatsapp-api-tutorial#10]
Hii, thankyou for your great tutorial on youtube! I tried some of your code through video and succeed to send personal message. But, I accidently remove WhatsApp last active user from my phone and after that, every time I try to execute code its give me Bad Request on console from Chrome. Can you give me some guide to fix this problem?

And also I have tried another github reference about whatsapp. Their have same error as I am. Is this error come from WhatsApp?

**Comment by refanka-inv** [comment]
The only way I solve this by re-clone the code. If there is another way, please let me know.

**Comment by ngekoding** [comment]
If you do Logout from your phone, you need to scan the qrcode again.

The API will automatically restart if the authentication is failure, to do this we have to use `restartIfAuthFail` configuration in the Client. I'm ready implementing it in this repo.

But, the important thing is we must wait for several time to get the API restart. 

The another solution is, we do remove the file whatsapp-session.json and re-run the app. But I personally use the first solution.

Hope this help you.
