### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LukasCCB** [ngekoding/whatsapp-api-tutorial#102]
Hello. How i can Add number to a group, remove number in a group.
And, how to get Group Participants number?

**Comment by ngekoding** [comment]
You can found some group features example here: https://github.com/pedroslopez/whatsapp-web.js/blob/main/example.js
And don't forget to check the official documentation: https://docs.wwebjs.dev/GroupChat.html

**Comment by LukasCCB** [comment]
> You can found some group features example here: https://github.com/pedroslopez/whatsapp-web.js/blob/main/example.js
> And don't forget to check the official documentation: https://docs.wwebjs.dev/GroupChat.html

To add/remove user to a group not have a example. but, thx for reply.
