### ISSUE TITLE
failed sendMessage new number

### ISSUE THREAD

**Issue by saifulcoder** [ngekoding/whatsapp-api-tutorial#105]
> // Send message
app.post('/send-message', [
  body('number').notEmpty(),
  body('message').notEmpty(),
], async (req, res) => {
  const errors = validationResult(req).formatWith(({
    msg
  }) => {
    return "jare kene error " + msg;
  });
  if (!errors.isEmpty()) {
    return res.status(422).json({
      status: false,
      message: errors.mapped()
    });
  }
  const number = phoneNumberFormatter(req.body.number);
  const message = req.body.message;
  const isRegisteredNumber = await checkRegisteredNumber(number);
  if (!isRegisteredNumber) {
    return res.status(422).json({
      status: false,
      message: 'The number is not registered'
    });
  }
  client.sendMessage(number, message).then(response => {
    res.status(200).json({
      status: true,
      response: response
    });
  }).catch(err => {
    res.status(500).json({
      status: false,
      response: err
    });
  });
});

saya mengalami kegagalan mengirim pesan ke nomor yang baru, yang belum pernah melakukan chat sebelumnya 
dan return responds 
`{"status":false,"response":{}}`
apa yang harus saya lakukan?
mohon bantuannya

**Comment by LucasSilverio** [comment]
npm update solve #104

**Comment by LucasSilverio** [comment]
npm update

**Comment by saifulcoder** [comment]
> npm update

wow worked
thanks....
