### ISSUE TITLE
errror Failed to launch the browser process! di VPS centos7

### ISSUE THREAD

**Issue by masngud** [ngekoding/whatsapp-api-tutorial#106]
[root@adminMlG whatsapp-api]# npm run start

> whatsapp-api@1.0.0 start
> node app.js

/var/www/html/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
[0909/015406.179949:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

    at onClose (/var/www/html/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
    at Interface.<anonymous> (/var/www/html/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)
    at Interface.emit (node:events:406:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:406:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[root@adminMlG whatsapp-api]#

mohon bantuan nya..

**Comment by ngekoding** [comment]
Coba dibaca baik-baik pesan errornya.

**Comment by masngud** [comment]
siap pak..saya cek lagi...
jazakumulloh qhoir..🙏

**Comment by masngud** [comment]
> [root@adminMlG whatsapp-api]# npm run start
> 
> > whatsapp-api@1.0.0 start
> > node app.js
> 
> /var/www/html/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197
> reject(new Error([
> ^
> 
> Error: Failed to launch the browser process!
> [0909/015406.179949:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> 
> ```
> at onClose (/var/www/html/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
> at Interface.<anonymous> (/var/www/html/whatsapp-api/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)
> at Interface.emit (node:events:406:35)
> at Interface.close (node:readline:586:8)
> at Socket.onend (node:readline:277:10)
> at Socket.emit (node:events:406:35)
> at endReadableNT (node:internal/streams/readable:1343:12)
> at processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```
> 
> [root@adminMlG whatsapp-api]#
> 
> mohon bantuan nya..

problem is solved
 add in client
puppeteer: {
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-accelerated-2d-canvas',
      '--no-first-run',
      '--no-zygote',
      '--single-process', // <- this one doesn't works in Windows
      '--disable-gpu'
    ],
  },

problem solved
