### ISSUE TITLE
bagaimana cara forward chat masuk ke nomor yg sudah ditentukan?

### ISSUE THREAD

**Issue by xmediateam** [ngekoding/whatsapp-api-tutorial#112]
bagaimana cara forward chat masuk ke nomor yg sudah ditentukan?
thanks

**Comment by ngekoding** [comment]
Bisa gunakan method forward dari object Message, contohnya seperti berikut:

```js
client.on('message', msg => {
  msg.forward('tujuan');
});
```

Parameter tujuan bisa berupa ChatID atau Chat, lebih jelasnya bisa merujuk ke [dokumentasi](https://docs.wwebjs.dev/Message.html#forward).

**Comment by xmediateam** [comment]
terimakasih sudah menjawab,  sya sudah mulai ada pandangan,
bolehkan sya minta contoh penggunaan parameter nya? terimakasih

**Comment by xmediateam** [comment]
sudah bisa terforward terimakasih.
kalau misalkan ada data seperti ini
nama : ngekoding
misalkan saya mau forward ngekoding nya saja apakah bisa? metode apa yg harus sya pakai, tlong di bantu terimakasih

**Comment by ngekoding** [comment]
Caranya akan spesifik tergantung dari aturan penulisannya, text processing istilahnya. 
Misal dengan contoh yang disebutkan:

**nama : ngekoding**

Maka prosesnya bisa dengan melakukan split berdasarkan karakter titik dua, kemudian ambil kata pada index 1. Contoh implementasinya.

```js
const text = 'nama : ngekoding';
const texts = text.split(':')
const result = texts[1];

console.log(result); // ngekoding
```

**Comment by xmediateam** [comment]
terimakasih,
kalau misalkan dalam kasus seperti ini,
kita menyediakan format
Nama :
lalu client membalas
Nama : ngekoding

cara mengambil data yg random seperti itu bagaimana ya? terimakasih

**Comment by ngekoding** [comment]
Sama seperti yang saya sebutkan sebelumnya.

**Comment by xmediateam** [comment]
sudah bisa berjalan, terimakasih,
mau tanya untuk id grup cara melihat dimana ya? sya coba cari tidak ketemu, terimakasih

**Comment by ngekoding** [comment]
Silahkan baca disini https://github.com/ngekoding/whatsapp-api-tutorial#send-message-to-group

**Comment by xmediateam** [comment]
maksud sya yg id xxx-xxx@g.us itu Pak

**Comment by ngekoding** [comment]
Silahkan dbaca dengan baik dan lengkap, sudah dijelaskan pada link tersebut.

**Comment by xmediateam** [comment]
terimakasih atas panduannya
