### ISSUE TITLE
session destroyed ketika hp kita log lout

### ISSUE THREAD

**Issue by masngud** [ngekoding/whatsapp-api-tutorial#114]
bismlillah,
pagi min...utk session destroyed pas hp logout bagaimana ya..?..
menset file whatsapp-session.json empty.
tks..

**Comment by ngekoding** [comment]
Maksudnya bagaimana, saya belum jelas?

**Comment by masngud** [comment]
delete file whatsapp-session.json ketika WA kita log out dr scan qr sebelumnya.

**Comment by ngekoding** [comment]
Apakah maksudnya mau menghapus file session ketika di HP logout?

**Comment by masngud** [comment]
iya betul..

**Comment by ngekoding** [comment]
Saya tidak tahu pasti masalahnya dimana, karena fungsi untuk menghapus file session sudah ada di dalam app.js. Silahkan diperhatikan pada bagian ini https://github.com/ngekoding/whatsapp-api-tutorial/blob/0ff06677d583c7f33f88664873b3c2768a886447/app.js#L154

**Comment by masngud** [comment]
ok admin..tks
