### ISSUE TITLE
Uncaught TypeError: $(...).read is not a function     <anonymous> http://localhost:8000/:18 localhost:8000:18:13     <anonymous> http://localhost:8000/:18 GEThttp://localhost:8000/favicon.ico

### ISSUE THREAD

**Issue by Koreansy12** [ngekoding/whatsapp-api-tutorial#115]
![Screenshot from 2021-09-29 10-05-28](https://user-images.githubusercontent.com/68386928/135196199-ba98e383-03d9-4668-a3ee-ae6171ac62ac.png)

![Screenshot from 2021-09-29 10-07-56](https://user-images.githubusercontent.com/68386928/135196420-ad791be3-6e43-4469-9c24-6d972fb3ace7.png)

![Screenshot from 2021-09-29 10-06-33](https://user-images.githubusercontent.com/68386928/135196319-14e663cd-8102-41c5-a206-3513c0c2df3b.png)

**Comment by ngekoding** [comment]
Typo, harusnya **ready** bukan **read**. Silahkan diperhatikan lagi contohnya.
