### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read properties of undefined (readin g 'default')

### ISSUE THREAD

**Issue by risqiRPL** [ngekoding/whatsapp-api-tutorial#134]
Waktu scan barcode muncul pesan error gan

**Comment by heriistantoo** [comment]
![image](https://user-images.githubusercontent.com/17525413/143875875-5de5a69b-279d-486c-b47a-6e12930e4268.png)

Sama, saya juga dapat. Solusinya gimana ya??

**Comment by heriistantoo** [comment]
Alhamdulilah ketemu solusi, tinggal upgrade dependencies whatsapp-web.js ke 1.15.2

`npm i whatsapp-web.js@latest`

Sumber : [https://github.com/pedroslopez/whatsapp-web.js/issues/1019](url)

**Comment by risqiRPL** [comment]
Terimakasih, sudah bisa

**Comment by ngekoding** [comment]
Sepertinya butuh kasih catatan nih, agar memastikan library yang dipakai adalah versi terakhir. Terima kasih.
