### ISSUE TITLE
Can you send media to a group?

### ISSUE THREAD

**Issue by jzvi12** [ngekoding/whatsapp-api-tutorial#139]
Can you send media to the group endpoint? If not available in the repo, can you please provide sample code to add it to app.js?
Thanks

**Comment by ngekoding** [comment]
Actually the idea is still same, the only different is you need to use Group ID (in general: Chat ID) for sending the message both for regular message and media message.

So, you can combine the idea from `/send-media` and `/send-group-message`

Here is the code for sending the media:

https://github.com/ngekoding/whatsapp-api-tutorial/blob/f9f660ba919b10a55d142e8377ab7d3b14a9a89e/app.js#L213-L244

And you only need to change the `number` with Chat ID like in sending group message.

https://github.com/ngekoding/whatsapp-api-tutorial/blob/f9f660ba919b10a55d142e8377ab7d3b14a9a89e/app.js#L279

**Comment by jzvi12** [comment]
Thanks! I came up with the following based on your suggestion. Seems to be working fine when sending an mp3 audio file to a group:
```javascript
// Send media to group
app.post('/send-media-group', async (req, res) => {
  let chatId = req.body.id;
  //const message = req.body.message;
  const caption = req.body.caption;
  const fileUrl = req.body.file;

  let mimetype;
  const attachment = await axios.get(fileUrl, {
    responseType: 'arraybuffer'
  }).then(response => {
    mimetype = response.headers['content-type'];
    return response.data.toString('base64');
  });

  const media = new MessageMedia(mimetype, attachment, 'Media');

  client.sendMessage(chatId, media, {
    caption: caption
  }).then(response => {
    res.status(200).json({
      status: true,
      response: response
    });
  }).catch(err => {
    res.status(500).json({
      status: false,
      response: err
    });
  });
});
```

cURL command used:
`curl --location --request POST 'http://127.0.0.1:8000/send-media-group' --form 'id="124868028627229737@g.us"' --form 'file="https://example.com/MP3/test.mp3"'`

JSON response:
```
{
    "status": true,
    "response": {
        "mediaKey": "7GKARamw7nmhdMNk8kVmFrn0fa3hqrsmsOkZWlPuMHI=",
        "id": {
            "fromMe": true,
            "remote": {
                "server": "g.us",
                "user": "124868028627229737",
                "_serialized": "124868028627229737@g.us"
            },
            "id": "42057E0FB1B7241EF3797D7C02A31502",
            "_serialized": "true_124868028627229737@g.us_42057E0FB1B7241EF3797D7C02A31502"
        },
        "ack": 0,
        "hasMedia": true,
        "body": "",
        "type": "audio",
        "timestamp": 1640021731,
        "from": "1987654321@c.us",
        "to": "124868028627229737@g.us",
        "deviceType": "android",
        "isForwarded": false,
        "forwardingScore": 0,
        "isStarred": false,
        "fromMe": true,
        "hasQuotedMsg": false,
        "vCards": [],
        "mentionedIds": []
    }
}
```

Anything else to improve this code?
