### ISSUE TITLE
error UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed

### ISSUE THREAD

**Issue by myhardez** [ngekoding/whatsapp-api-tutorial#14]
saya sudah coba sampai tutorial ke 3 tip trik,
sudah bisa mengirim pesan via API
sy mau tanya, 
ketika bersamaan whatsapp login juga di browser, selalu muncul error spt ini:
-----------------------------
(node:16164) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
    at CDPSession.send (D:\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:195:35)
    at ExecutionContext._evaluateInternal (D:\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:200:50)
    at ExecutionContext.evaluate (D:\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:27)
    at DOMWorld.evaluate (D:\whatsapp-api\node_modules\puppeteer\lib\cjs\puppeteer\common\DOMWorld.js:90:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:16164) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

--------------------
kira2 ada kesalahan apa yaa
terima kasih

**Comment by ngekoding** [comment]
Seperti yang saya singgung di awal tutorial, bahwa konsep dari API yang kita buat adalah seperti Whatsapp Web, maka dari sisi penggunaan Whatsapp Web juga tidak mengizinkan menjalankan satu akun di banyak tab/browser di dalam satu komputer.

Maka solusi yang bisa kita berikan saat ini adalah menjalankan API melalui komputer yang berbeda.

Semoga menjawab.

**Comment by myhardez** [comment]
baik terima kasih atas infonya
saya sudah coba menjalankan API melalui komputer yang berbeda **YAITU Dengan menggunakan VPS...**
lalu coba login di komputer rumah, dan ada pesan error seperti diatas

saya mau tanya, Bagaimana error handlingnya di VPS..  ketika Whatsapp login di komputer rumah
