### ISSUE TITLE
apakah bisa methode scan qrcode diganti dengan nomor wa terdaftar?

### ISSUE THREAD

**Issue by windugi** [ngekoding/whatsapp-api-tutorial#143]
Halo admin mau tanya nih apakah bisa methode scan qrcode nya diganti dengan nomor wa saja jadi tidak perlu scan qrcode?

**Comment by ngekoding** [comment]
Konsep yang digunakan adalah sama dengan penggunaan Whatsapp Web, sehingga harus dengan scan qr code.

**Comment by windugi** [comment]
> Konsep yang digunakan adalah sama dengan penggunaan Whatsapp Web, sehingga harus dengan scan qr code.
berarti harus scan qr code ya dulu ya bang biar dapet nomor pengirimnya?
