### ISSUE TITLE
Cannot read property 'client' of undefined //send-message

### ISSUE THREAD

**Issue by firdausz27** [ngekoding/whatsapp-api-tutorial#147]
Ini untuk multiple devices,

ketika test POST ke localhost:8000/send-message,
tampil pesan error : "Cannot read property 'client' of undefined"

![image](https://user-images.githubusercontent.com/89822904/147202339-a2e8a3c3-8c79-4fd4-bae6-f354748e2ab5.png)

**Comment by ngekoding** [comment]
Silahkan ikuti tutorial terlebih dulu.
