### ISSUE TITLE
savedSessions.findIndex is not a function

### ISSUE THREAD

**Issue by Marzuki5** [ngekoding/whatsapp-api-tutorial#15]
erro saat akan menampilkan qrcode di multiple device

const sessionIndex = savedSessions.findIndex(sess => sess.id == id);

TypeError: savedSessions.findIndex is not a function
    at createSession (D:\wasem\app-multiple-device.js:129:38)
    at Socket.<anonymous> (D:\wasem\app-multiple-device.js:163:5)
    at Socket.emit (events.js:315:20)
    at D:\wasem\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ngekoding** [comment]
Silahkan buat file dengan nama `whatsapp-sessions.json`, dan berikan isinya berupa array kosong `[]` terlebih dulu.

Hal ini bisa dilihat pada file .gitignore, dan juga pada tutorial sudah saya jelaskan prosesnya.

Semoga terjawab.
