### ISSUE TITLE
Cara Otomatis Kirim File Saat Bot Menerima Pesan Tertentu

### ISSUE THREAD

**Issue by QomariSanjaya** [ngekoding/whatsapp-api-tutorial#154]
Misal saat ada yang mengirim pesan "DOWNLOAD" maka script akan secara otomatis mengirim file yang sudah disiapkan di server kepada si pengirim pesan.

**Comment by gotopa** [comment]
logic nya sama seperti auto reply
https://wwebjs.dev/guide/#replying-to-messages

**Comment by ngekoding** [comment]
Tinggal menggabungkan cara auto reply pada event on message dengan saat mengirim pesan media.

Perhatikan pada method untuk mengirim pesan.
