### ISSUE TITLE
localhost/send message not working

### ISSUE THREAD

**Issue by preet665** [ngekoding/whatsapp-api-tutorial#155]
![Screenshot 2021-12-31 212348](https://user-images.githubusercontent.com/47426321/147831340-ec7ecc8e-61a4-41a0-8b2d-c6da6789c88b.png)
![image](https://user-images.githubusercontent.com/47426321/147831352-fd0f13f9-94e9-468b-b479-38c0f241aab7.png)

**Comment by gotopa** [comment]
coba untuk number tanpa tanda +

**Comment by dirgareborn** [comment]
type the whatsapp number without using the (+) sign followed by the remote server
919601290320@c.us

**Comment by ngekoding** [comment]
Please watch the tutorials first for better understanding.
