### ISSUE TITLE
Save Session on MariaDB or Mysql

### ISSUE THREAD

**Issue by mohammadelarief** [ngekoding/whatsapp-api-tutorial#160]
Salam kak,

bagaimana cara menyimpan session di MariaDB/Mysql sebagai ganti Postgress?

**Comment by ngekoding** [comment]
Dari sisi konsep sama, tinggal menyesuaikan library-nya dan mengikuti sesuai library tersebut. Misal bisa gunakan library ini https://www.npmjs.com/package/mysql2

**Comment by mohammadelarief** [comment]
Selalu Gagal karena di MariaDB tidak ada type data JSONB tidak sperti Postgress
![image](https://user-images.githubusercontent.com/39216680/153540396-c9027860-dc88-4f1e-9b9d-21be1f9d586e.png)

**Comment by ngekoding** [comment]
Idenya adalah sebelum disimpan ke DB, ubah dulu menjadi string biasa, kemudian nanti ketika diambil datanya baru diubah lagi menjadi JSON.

```js
// Ubah menjadi string
const sess = JSON.stringify(session);
```

Kemudian sebaliknya ketika dibaca:

```js
// Parse menjadi JSON
const session = JSON.parse(sess); // sess adalah data yang didapat dari DB
```

**Comment by mohammadelarief** [comment]
Ok siap kak,
Terima kasih 👍👍
