### ISSUE TITLE
Express-file-upload: Request is not eligible for file upload!

### ISSUE THREAD

**Issue by brilyanilhamsadewo** [ngekoding/whatsapp-api-tutorial#164]
> whatsapp-api@1.0.0 start
> node app.js

(node:115704) DeprecationWarning: options.session is deprecated and will be removed in a future release due to incompatibility with multi-device. Use the LocalAuth authStrategy, don't pass in a session as an option, or suppress this warning by using the LegacySessionAuth strategy explicitly (see https://wwebjs.dev/guide/authentication.html#legacysessionauth-strategy).
(Use `node --trace-deprecation ...` to show where the warning was created)
App running on *: 8000
Express-file-upload: Request is not eligible for file upload!
Express-file-upload: Request is not eligible for file upload!
Express-file-upload: Request is not eligible for file upload!

**Comment by AntoniusArief** [comment]
You have to replace   
debug: true  
into   
debug: false

```
app.use(fileUpload({
  debug: false 
}));
```

**Comment by ngekoding** [comment]
Please use the latest code, I already make an update and a tutorial on YouTube.
