### ISSUE TITLE
api postman 500 internal server error

### ISSUE THREAD

**Issue by AntoniusArief** [ngekoding/whatsapp-api-tutorial#165]
Good day,

I'm trying to follow your instruction from your youtube, but i found 500 internal server error error when trying to send message using postman.

In second trial, i just copied your code from github, QR can be scanned successfully, but when send message using postman, i've get same error. 500 internal server error.

Is there any steps that I missed?

Thank you,

```
{
	"status": false,
	"response": {}
}

```

**Comment by ngekoding** [comment]
Please use the latest code, I already make an update and a tutorial on YouTube.
