### ISSUE TITLE
QR Code tidak segera muncul di web

### ISSUE THREAD

**Issue by yanuarkrisna** [ngekoding/whatsapp-api-tutorial#166]
DeprecationWarning: options.session is deprecated and will be removed in a future release due to incompatibility with multi-device. Use the LocalAuth authStrategy, don't pass in a session as an option, or suppress this warning by using the LegacySessionAuth strategy explicitly (see https://wwebjs.dev/guide/authentication.html#legacysessionauth-strategy).
(Use `node --trace-deprecation ...` to show where the warning was created)

itu maksudnya gimana ya gan? apa mungkin itu penyebab QRcode saya tidak segera muncul di web nya?
Terimakasih

**Comment by ngekoding** [comment]
Silakan bisa menggunakan kode terbaru mas, saya sudah membuat penyesuaian diserta video tutorial di YouTube. Semoga membantu.
