### ISSUE TITLE
app-multiple-device.js does not work

### ISSUE THREAD

**Issue by jcchua** [ngekoding/whatsapp-api-tutorial#169]
Hi Nur Muhammad, 

Your multi device program does not work anymore after pedroslopez upgraded his to whatsapp-web.js v1.16.0 and above.  
Hope to see your update soon.

**Comment by ngekoding** [comment]
Are you using MD version or a regular?

**Comment by jcchua** [comment]
I am using MD version.

**Comment by ngekoding** [comment]
Sorry this repo is not supported it yet.

**Comment by ngekoding** [comment]
**Update:** it is supported now! You can try to use the latest code, and for the explanation please watch the tutorial already listed in readme.
