### ISSUE TITLE
QrCode tidak muncul

### ISSUE THREAD

**Issue by rizqifeb** [ngekoding/whatsapp-api-tutorial#17]
Waktu saya jalankan,mengapa tidak muncul logo QR nya ya? Di command prompt muncul tulisan "Request is not eligible for file upload" seperti gambar terlampir.

Lampiran SS.
[https://ibb.co/0DyjmZw](https://ibb.co/0DyjmZw)
[https://ibb.co/tK55GRp](https://ibb.co/tK55GRp)

Terimakasih.

**Comment by ngekoding** [comment]
Untuk memudahkan, biasakan untuk melihat error di Inspect > Console. 

Kemudian, untuk masalah yang didapat, biasanya karena penggunaan versi socket.io yang berbeda antara yang di server dan di client. Kemarin saya sudah melakukan penyesuaian di packages.json dan file .html, silahkan bisa dicek atau gunakan kode terbaru dari repo ini.

**Comment by natsirasrafi** [comment]
cara benerin versi socket.io yang berbeda gimana? dan cek server versi verapa dan clientya

**Comment by ngekoding** [comment]
Yang di server cek pada file `package.json`, adapun yang di client pada file HTMLnya (index.html, index-multiple-device.html), disana ada tag script untuk socket juga.
