### ISSUE TITLE
DeprecationWarning: options.session is deprecated

### ISSUE THREAD

**Issue by QomariSanjaya** [ngekoding/whatsapp-api-tutorial#171]
`DeprecationWarning: options.session is deprecated and will be removed in a future release due to incompatibility with multi-device. Use the LocalAuth authStrategy, don't pass in a session as an option, or suppress this warning by using the LegacySessionAuth strategy explicitly (see https://wwebjs.dev/guide/authentication.html#legacysessionauth-strategy).`

Dapat pesan error seperti itu

**Comment by ngekoding** [comment]
Maaf sepertinya ini berkaitan dengan versi terbaru whatsapp-web.js yang sudah mensupport multi-device beta. Bisa ikuti link yang tertera pada error tersebut.

Saat ini, kode pada repositori ini belum menggunakan multi-device beta, sehingga tidak bisa berjalan. Silakan bisa disesuaikan.

**Comment by ngekoding** [comment]
Maaf sepertinya ini berkaitan dengan versi terbaru whatsapp-web.js yang sudah mensupport multi-device beta. Bisa ikuti link yang tertera pada error tersebut.

Saat ini, kode pada repositori ini belum menggunakan multi-device beta, sehingga tidak bisa berjalan. Silakan bisa disesuaikan.

**Comment by ngekoding** [comment]
Silakan menggunakan kode terbaru dari repositori ini, sudah disesuaikan dan ditambahkan video tutorial agar lebih mudah untuk dipahami. Semoga membantu.
