### ISSUE TITLE
perangkat masih terkait di perangkat tertaut tapi ketika buka heroku minta qr lagi itu kenapa ya ?

### ISSUE THREAD

**Issue by Dhimas004** [ngekoding/whatsapp-api-tutorial#172]

**Comment by ngekoding** [comment]
Apakah sudah mengikuti video terkait perbaikan penyimpanan session untuk Heroku?

**Comment by Dhimas004** [comment]
> Apakah sudah mengikuti video terkait perbaikan penyimpanan session untuk Heroku?

oh ga liat bang maaf, makasih bang responnya

**Comment by ngekoding** [comment]
Sama-sama mas 👍🏻
