### ISSUE TITLE
Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.

### ISSUE THREAD

**Issue by whizydev** [ngekoding/whatsapp-api-tutorial#173]
Normal app.js works like expected. But want to use multi device option (so we can switch the smartphone offline). I get this error after scanning QR code in multi device file

Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.

Also this deprecation warning
DeprecationWarning: options.session is deprecated and will be removed in a future release due to incompatibility with multi-device. Use the LocalAuth authStrategy, don't pass in a session as an option, or suppress this warning by using the LegacySessionAuth strategy explicitly (see https://wwebjs.dev/guide/authentication.html#legacysessionauth-strategy).

Can someone help me? Thanks!

**Comment by diazzaid** [comment]
> Normal app.js works like expected. But want to use multi device option (so we can switch the smartphone offline). I get this error after scanning QR code in multi device file
> 
> Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.
> 
> Also this deprecation warning DeprecationWarning: options.session is deprecated and will be removed in a future release due to incompatibility with multi-device. Use the LocalAuth authStrategy, don't pass in a session as an option, or suppress this warning by using the LegacySessionAuth strategy explicitly (see https://wwebjs.dev/guide/authentication.html#legacysessionauth-strategy).
> 
> Can someone help me? Thanks!

update md
https://github.com/diazzaid/whatsapp-api-tutorial/blob/master/app.js

**Comment by ngekoding** [comment]
Sorry, the app-multiple-device mean on this repository to use many whatsapp account, not the Whatsapp Multi Device Beta. And I keep this code to use a regular version of whatsapp, just because it related to the tutorials I made.

I don't know when I can update the code + tutorials for supporting the multi device beta version. Still can't found the right time.

**Comment by whizydev** [comment]
Thanks for your replies. Multi device beta version will be a really good feature to add. Pedro already integrated this?

**Comment by ngekoding** [comment]
Please use the latest code, I already make an update and a tutorial on YouTube.

**Comment by whizydev** [comment]
> Please use the latest code, I already make an update and a tutorial on YouTube.

Thank you! It is also possible to link the accounts and switch device off? Like multi device whatsapp beta?

**Comment by whizydev** [comment]
Sounds good. I downloaded your code and setup a test. I'm getting this error on send-message:
TypeError: Cannot read properties of undefined (reading 'client') - How to fix that?

**Comment by ngekoding** [comment]
It is important to follow the tutorial for detail instruction, for the app-multiple-account.js you need to define/include the sender name (an ID when creating the client).

Please take a look here https://github.com/ngekoding/whatsapp-api-tutorial/blob/70707d7fdb77054af4c74c53dbda29024c511869/app-multiple-account.js#L211

**Comment by whizydev** [comment]
Thank you. It works, would be good to show a Postman test in the end. I thought sender is phone number. Other question: How can I use the function: isRegisteredUser / checkRegisteredNumber in multidevice script? I see it got removed?

**Comment by ngekoding** [comment]
Let's talk about different topic in different issue.
