### ISSUE TITLE
QR tidak muncul saat mangubah session menjadi saveSession

### ISSUE THREAD

**Issue by Dhimas004** [ngekoding/whatsapp-api-tutorial#175]
Pada saat saya mengubah session di bagian const client app.js QR tidak muncul, namun setelah saya hapus atau saya kembalikan isinya ke sessionCfg QR muncul. itu masalahnya kenapa ya bang ? apa karena saya meloncat tutorial dari deploy ke fix session heroku ?

**Comment by ngekoding** [comment]
Saya kurang jelas maksudnya bagaimana mas, mungkin bisa disertakan kodenya.

**Comment by Dhimas004** [comment]
const client = new Client({
    puppeteer: {
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-accelerated-2d-canvas",
        "--no-first-run",
        "--no-zygote",
        "--single-process", // <- this one doesn't works in Windows
        "--disable-gpu",
      ],
      headless: true,
    },
    **session: saveSession**
  });

dibagian yang saya bold ketika saya isi session: saveSession QRnya tidak mau muncul, tetapi ketika saya hapus atau saya kemablikan lagi menjadi session: sessionCfg QRnya baru muncul

**Comment by ngekoding** [comment]
Sepertinya ada kesalahpahaman mas, jika mengikuti yang ada di Heroku itu, itu namanya **savedSession** (pakai d), jadi itu membaca session yang berasal dari DB. Intinya adalah sama, tapi hanya perbedaan letak penyimpanannya.

Untuk bagian itu ada beberapa perbedaan, silakan bisa disimak dengan baik tutorialnya.

**Comment by Dhimas004** [comment]
> Sepertinya ada kesalahpahaman mas, jika mengikuti yang ada di Heroku itu, itu namanya **savedSession** (pakai d), jadi itu membaca session yang berasal dari DB. Intinya adalah sama, tapi hanya perbedaan letak penyimpanannya.
> 
> Untuk bagian itu ada beberapa perbedaan, silakan bisa disimak dengan baik tutorialnya.

untuk nama variabelnya itu saya rubah mas ke saveSession. bisa minta tolong di cek-in ngga mas codingannya. sudah saya invite ke repo saya ya mas

**Comment by ngekoding** [comment]
Silakan bisa pastekan saja kodenya disini mas, kode yang bersesuaian saja tidak usah semuanya.
