### ISSUE TITLE
not suport session

### ISSUE THREAD

**Issue by abdulaziz1999** [ngekoding/whatsapp-api-tutorial#177]
DeprecationWarning: options.session is deprecated and will be removed in a future release due to incompatibility with multi-device. Use the LocalAuth authStrategy, don't pass in a session as an option, or suppress this warning by using the LegacySessionAuth strategy explicitly (see https://wwebjs.dev/guide/authentication.html#legacysessionauth-strategy). (Use `node --trace-deprecation ...` to show where the warning was created) (node:18) DeprecationWarning: options.session is deprecated and will be removed in a future release due to incompatibility with multi-device. Use the LocalAuth authStrategy, don't pass in a session as an option, or suppress this warning by using the LegacySessionAuth strategy explicitly (see https://wwebjs.dev/guide/authentication.html#legacysessionauth-strategy).

**Comment by ngekoding** [comment]
Already answered here https://github.com/ngekoding/whatsapp-api-tutorial/issues/176
