### ISSUE TITLE
How to check session with same name

### ISSUE THREAD

**Issue by RyanRyan99** [ngekoding/whatsapp-api-tutorial#181]
How do I check for sessions with the same name, so when the user inputs a session with the same name, it doesn't work

**Comment by ngekoding** [comment]
It is only need to use javascript find method, find the session with that given name, and if it found return an error (telling that the name is unavailable or already used).

```js
const id = 'primary'; // actually from user input

const found = sessions.find(session => session.id == id);

if (found) {
  // Return an error: the given ID already exists
}

// If the ID is available, so continue the process here
// ...
```
