### ISSUE TITLE
Brazil numbers not working properly

### ISSUE THREAD

**Issue by edilsonlsouza** [ngekoding/whatsapp-api-tutorial#182]
Hello, first I want to congratulate the auto! Thank you!

Here in Brazil the numbers have a 9 ahead.
When I use it with 9 it doesn't work. If I remove the 9 in front of the number it works perfectly!

55 81 88327966 = Success!
55 81 9 88327966 = Not working!

It cost!

**Comment by ngekoding** [comment]
First, I was never try to send a message to Brazilian number yet. So, we need to know the error message.

Let me know, if you send to that number with whatsapp app, does it works?

**Comment by edilsonlsouza** [comment]
> Let me know, if you send to that number with whatsapp app, does it works?

Yes!

Without the 9, yes it works! Returns code 200, without giving any error.
With the 9, It doesn't work! And returns code 200, without giving any error.

**Comment by ngekoding** [comment]
Is the number still same with and without 9?

**Comment by edilsonlsouza** [comment]
Yes!!

Thank you guys!

I solved it with this function in my module:

```
public function Trata_Numero($tel) {

        $tel = str_replace("-", "", $tel);
        $tel = str_replace("(", "", $tel);
        $tel = str_replace(")", "", $tel);
        $tel = str_replace("_", "", $tel);
        $tel = str_replace(" ", "", $tel);
        $tel = str_replace("+", "", $tel);
        $tel = trim($tel);

        if (strlen($tel) > 12) {

            $inicio = substr($tel, 0, 4);
            $fim =  substr($tel, -8);
            $tel = $inicio.$fim;
          
        }

        return $tel;

    }
```

**Comment by ngekoding** [comment]
Good! It is the like what we do in the number formatter helper.

You can make it simpler with regex for removing unnecessary characters:

https://github.com/ngekoding/whatsapp-api-tutorial/blob/349196744fa2a27ff37d3267754619b0ee1719e0/helpers/formatter.js#L3

The code above will remove all non-number characters.

**Comment by edilsonlsouza** [comment]
Thank you!
