### ISSUE TITLE
Does not record sections

### ISSUE THREAD

**Issue by edilsonlsouza** [ngekoding/whatsapp-api-tutorial#184]
Hello good people!

I followed the tutorial videos and adapted it to Mult-Device and the section is not recording.

Could you help me, see the picture!

https://imgur.com/a/mRNWVT9

Thankyou!

**Comment by ngekoding** [comment]
Sorry, because of the latest version of whatsapp-web.js, we can’t use session option anymore when creating the client.

You just need to use the authStrategy, please watch my last video tutorial for the details.
