### ISSUE TITLE
Hapus session

### ISSUE THREAD

**Issue by bayurex** [ngekoding/whatsapp-api-tutorial#188]
Bagaimana Hapus session ketika baru membuka wa api atau setelah menutupnya?

kalau make session yang lama masih agak paham, yang session versi baru agak bingung

**Comment by ngekoding** [comment]
Apakah intinya tidak ingin menyimpan sessionnya? Sehingga setiap kali dijalankan butuh untuk scan lagi?

**Comment by ngekoding** [comment]
Defaultnya memang seperti itu, jadi tidak perlu menggunakan LocalAuth.

Pada tutorial terakhir sudah saya jelaskan beberapa macam auth strategy yang bisa digunakan, dan defaultnya adalah NoAuth, yaitu session tidak disimpan.

**Comment by abdulaziz1999** [comment]
jika session tidak di simpan , brrti wa mendeteksi sessionnya dari mana ya?

**Comment by ngekoding** [comment]
Betul, peru scan lagi apabila koneksinya terputus (misal karena server restart).

**Comment by bayurex** [comment]
Kalo bikin fungsi logout dari node js nya bisa ga ya?
