### ISSUE TITLE
Setelah 1 hari standby , whatsapp scan qrcode ulang

### ISSUE THREAD

**Issue by poseidonwood** [ngekoding/whatsapp-api-tutorial#19]
Gimana caranya agar whatsapp api tidak scan qr code ulang?, padahal whatsapp sya tidak logout statusnya, setelah 1 hari sya biarkan tiba tiba suruh scan ulang di whatsapp api nya

**Comment by ngekoding** [comment]
Barangkali bisa dicek logs-nya, mungkin ada keadaan dimana penggunaan resource meningkat yang menyebabkan aplikasi crash sehingga direstart.
