### ISSUE TITLE
Express-file-upload: Request is not eligible for file upload!

### ISSUE THREAD

**Issue by asyary** [ngekoding/whatsapp-api-tutorial#190]
![Err](https://user-images.githubusercontent.com/84187014/161380341-2afee93e-dc08-4330-ad06-701ba696be9e.png)
Muncul error "Express-file-upload: Request is not eligible for file upload!". Masih file raw, belum ada yg diubah, module sudah up to date semua.

**Comment by asyary** [comment]
Sudah fix, kesalahan dari index.html nya karena versi socket.io yang berbeda.

`	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.4.1/socket.io.js" crossorigin="anonymous"></script>
`

**Comment by imamsuro** [comment]
You save my time @asyary. Thank you.
Thank you mr. @ngekoding BarokAllahu fik
