### ISSUE TITLE
Membuat button/tombol pada whutsupp

### ISSUE THREAD

**Issue by Arieumarella** [ngekoding/whatsapp-api-tutorial#192]
Hi min, 
Maaf saya seorang nyebelin, 
Saya  mau menginplemrntasikan button/tombol pada bot chat whatsapp saya, 
Apakah mimin ada contoh code sederhana untuk menciptakan tombol pada bot WhatsApp. 
Trimakasih 🙏

**Comment by ngekoding** [comment]
Silakan bisa lihat contohnya disini https://github.com/pedroslopez/whatsapp-web.js/blob/3a2acf71c21f5c4d68b7f59654606065b4f7efca/example.js#L188

**Comment by Arieumarella** [comment]
Trimakasih mimiin. 🙏
