### ISSUE TITLE
ID Menggunakan Angka atau Campuran QR Code tidak tampil

### ISSUE THREAD

**Issue by deprie2324** [ngekoding/whatsapp-api-tutorial#194]
saya memcoba untuk masukkan ID pada index multiple menggunakan nomor telp, tetapi QR Code tidak tampil, ketika menggunkan hurup QR Code tampil. 

Apakah ada solusi untuk masalah ini ?

**Comment by ngekoding** [comment]
Yang perlu dipahami adalah ID yang dimasukkan itu akan digunakan juga sebagai id/class dari tag HTML, dan jika hanya angka maka HTML tidak membenarkan itu. 

Itu sebabnya pada tutorial diberikan contoh menggunakan huruf.

Sehingga kesimpulannya tidak bisa dengan angka saja atau campuran dengan angka di depan.

Valid: `abc123`
Tidak valid: `123` atau `123abc`

**Comment by deprie2324** [comment]
Baik kang, akan saya coba untuk merubah pada bagian classnya, karena rencana saya untuk ID atau sender itu dimasukkan nomor hp clinet sehingga pada saat membut curl pada bagian sender di isikan nomor
