### ISSUE TITLE
client disconnected koneksi internet

### ISSUE THREAD

**Issue by riagie** [ngekoding/whatsapp-api-tutorial#2]
[08/11/2020 11:40:43.770]  Internet Device Client Connected
[08/11/2020 11:45:43.770] [LOG]    Starting
[08/11/2020 11:46:04.179] [LOG]    Received Authenticated Session
[08/11/2020 11:46:04.265] [LOG]    WhatsApp Web v 2.2045.15
[08/11/2020 11:46:04.266] [LOG]    WWebJS v 1.11.0
[08/11/2020 11:46:04.270] [LOG]    WhatsApp CONNECTED
[08/11/2020 11:46:04.837] [LOG]    WhatsApp Web { status: 200 }
[08/11/2020 11:46:04.845] [LOG]    Whatsapp Ready
[08/11/2020 11:50:04.845] Internet Device Client di Disconnected

Console + Chromium = tidak ada respon
client.on('disconnected', async (disconnected) => tidak berfungsi

![1](https://user-images.githubusercontent.com/20628086/98457430-c43e0f80-21b9-11eb-8696-7bf494af5fed.PNG)

apabila Chromium di reload manual
![2](https://user-images.githubusercontent.com/20628086/98457441-d455ef00-21b9-11eb-80e0-6c97abc4892e.PNG)

**Comment by galihdwi** [comment]
Saya coba barusan juga sama

**Comment by ngekoding** [comment]
@riagie @galihdwi Pakai source code dari repo ini?

**Comment by ngekoding** [comment]
Jika ada melakukan perubahan kode, silahkan disertakan kodenya untuk memudahkan.

**Comment by riagie** [comment]
> 
> 
> @riagie @galihdwi Pakai source code dari repo ini?

client.on('disconnected', async (disconnected) => {
	client.destroy();
	fs.rmdirSync(session_file_path, { recursive: true });
    console.error('WhatsApp: Was Logged Out', disconnected);
	setTimeout(() => {
		console.log('WhatsApp: Restarting');
	},5000);
	client.initialize();
});

**Comment by ngekoding** [comment]
Sepertinya saya ada lupa menyampaikan di video Tips dan Trik, ada pengaturan tambahan yang saya lakukan untuk memudahkan proses re-auth. 

Repo sudah saya update, bisa dicek.

Semoga terjawab.

**Comment by riagie** [comment]
> Sepertinya saya ada lupa menyampaikan di video Tips dan Trik, ada pengaturan tambahan yang saya lakukan untuk memudahkan proses re-auth.
> 
> Repo sudah saya update, bisa dicek.
> 
> Semoga terjawab.

baik, sya coba ya
