### ISSUE TITLE
WA Gateway Multiple Source Number

### ISSUE THREAD

**Issue by ccmks** [ngekoding/whatsapp-api-tutorial#200]
Apakah bisa meregistrasi dan scan QR code utk beberapa nomor WA yg berbeda dalam server yang sama? Apakah akan saling tabrakan?

**Comment by ngekoding** [comment]
Bisa, silakan bisa cek tutorial yang sudah tersedia untuk Multi Device.

https://youtu.be/5VfM9PvrYcE
