### ISSUE TITLE
Auto run npm run start:dev

### ISSUE THREAD

**Issue by ccmks** [ngekoding/whatsapp-api-tutorial#202]
Bagaimana cara d buat auto run untuk: npm run start:dev setiap kali setelah server direboot?

Terima kasih

**Comment by ngekoding** [comment]
Biasanya kami menggubakan package `pm2`, silakan bisa dicek.

**Comment by josephvoxone** [comment]
Masuk ke direktori path project. 
-  **pm2 start app.js**
- pm2 save
- pm2 startup [Biasanya muncul info disuruh masukkan command ke cli]
- Copas dan jalankan command

Dokumentasi bisa dilihat https://pm2.keymetrics.io/docs/usage/quick-start/
