### ISSUE TITLE
!groups Error

### ISSUE THREAD

**Issue by RAYHunts** [ngekoding/whatsapp-api-tutorial#209]
Error ketika command !groups

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'map')
    at Object.window.WWebJS.getChats (__puppeteer_evaluation_script__:350:36)
    at __puppeteer_evaluation_script__:2:40

**Comment by okuruu** [comment]
Aku juga ngalamin gini, apalagi pas send chat ke group

Error log juga persis sama seperti log di issues atas

**Comment by ngekoding** [comment]
Setelah saya telusuri, masalah ini memang belum terselesaikan di pengembangnya. Termasuk untuk `getContacts` juga tidak bisa dengan error yang sama.

Telah ada PR, tapi terlihat tidak diterima.

**Comment by ngekoding** [comment]
Bug ini sudah diperbaiki pada versi `v1.16.7`, sehingga solusinya cukup update library-nya `npm update whatsapp-web.js`

Ref: https://github.com/pedroslopez/whatsapp-web.js/pull/1503
