### ISSUE TITLE
QR Code tidak bisa nampil 

### ISSUE THREAD

**Issue by SATRIA-ADHI-NUGRAHA** [ngekoding/whatsapp-api-tutorial#21]
udah saya restart awalnya bisa muncul, kesini-sini malah gak bisa muncul qr codenya saya pake windows..

**Comment by ngekoding** [comment]
Silahkan berikan informasi yang lebih detail. Cek juga Console pada browser, barangkali ada masalah di socket-nya.

**Comment by SATRIA-ADHI-NUGRAHA** [comment]
console di browser gak ada yang eror min

**Comment by doronmas** [comment]
How Can we receive back messages via
webhook
thanks Doron

**Comment by ngekoding** [comment]
Silahkan berikan informasi yang lebih detail.

**Comment by ngekoding** [comment]
> How Can we receive back messages via
> webhook
> thanks Doron

Please create another issue.
