### ISSUE TITLE
Send buttons 

### ISSUE THREAD

**Issue by masngud** [ngekoding/whatsapp-api-tutorial#213]
malam min..ada contoh script Send buttons kah..?

**Comment by ngekoding** [comment]
Coba cek issue yang sudah ada, sudah pernah dibahas.

**Comment by masngud** [comment]
_Silakan bisa lihat contohnya disini https://github.com/pedroslopez/whatsapp-web.js/blob/3a2acf71c21f5c4d68b7f59654606065b4f7efca/example.js#L188_

tks min
