### ISSUE TITLE
Failure using this utility

### ISSUE THREAD

**Issue by jhernancanom** [ngekoding/whatsapp-api-tutorial#214]
I tried some two or three times to read the QR image, but failed; until third or forth I got !!!

The I go to Auth/CheckAuth: failed, Auth/GetQR: failed....

I try to send a message --via web service on port 8000--: failed....

Say me what is wrong in my scenario.

Thanks.

![4-npm-run-start-dev-(a)](https://user-images.githubusercontent.com/5818845/177112928-f014cbe0-9fe6-4e33-8f92-275c25769845.png)

![4-npm-run-start-dev-(b)](https://user-images.githubusercontent.com/5818845/177113091-5acc7bd9-48b0-42f8-9618-239a3dfd85bd.PNG)

![4-npm-run-start-dev-(d)](https://user-images.githubusercontent.com/5818845/177113934-080117f9-536c-4a9e-b36d-74724d9a02db.PNG)

**Comment by ngekoding** [comment]
I think you need to watch the tutorials first for better understanding.

**Comment by ngekoding** [comment]
Btw we don't setup any auth mechanism.

After running the script, you must scan the qr code from the browser (open localhost:8000). And after authenticated you can use Postman to test sending the message.

And use Node version 14 or 16.

**Comment by jhernancanom** [comment]
I follow these instructions (first image here), and I use this version (shown in called "image 2", from first message and attached here). I run those "CLI" commands in admin-mode. 

Ok: I do not need " http://localhost:8000\auth\checkout " nor " http://localhost:8000\auth\getqr " .
I have realized that with only need " http://localhost:8000 " I can get the QR image.

But --as show in images from first message-- after read the QR image (see AUTHENTICATED from first message and **_not_** attached here), I am receiving 
" **Express-file-upload: Request is not elegible for file upload** ".

What does it mean and how can I resolve?

![Instructions](https://user-images.githubusercontent.com/5818845/177244694-b327d75f-bad2-4e93-a277-ba0f48b1ef7b.png)

![image](https://user-images.githubusercontent.com/5818845/177244884-d3e21194-7d0c-4ceb-8a04-75490cb85fb3.png)

**Comment by jhernancanom** [comment]
Ok: I got send messages with both Postman and my prog language via web service.

With every message that I send I got 

Express-file-upload: Request is not eligible for file upload!

and I see in CLI black-window:

(node:8532) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnected listeners added to [Client]. Use emitter.setMaxListeners() to increase limit

**Comment by jhernancanom** [comment]
Fine.
