### ISSUE TITLE
e.isLid is not a function

### ISSUE THREAD

**Issue by akbar346** [ngekoding/whatsapp-api-tutorial#219]
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/58684819/177905183-22c06c49-052f-4b9a-8ade-a852e3d22637.png">

Assalamu'alaikum mas Muhammad
Saya ada problem seperti ini mas, kira2 kenapa ya mas?
Karena sebelum2nya bisa tetapi per hari ini tidak bisa

**Comment by akbar346** [comment]
Alhamdulillah sudah bisa mas.
Jadi pada bagian function **getNumberId**, diganti menjadi..

async getNumberId(number) {
        if (!number.endsWith('@c.us')) {
            number += '@c.us';
        }

        return await this.pupPage.evaluate(async number => {
            // Replace this line
            // const result = await window.Store.QueryExist(number); 
            
            // With these two lines
            const wid = window.Store.WidFactory.createWid(number);
            const result = await window.Store.QueryExist(wid);
            
            if (!result || result.wid === undefined) return null;
            return result.wid;
        }, number);
    }

**Comment by ngekoding** [comment]
Wa'alaikumussalam

Mantaps 👍🏻 

Sebagai solusi sementara cara tersebut tidak mengapa, tapi harap diperhatikan ketika melakukan update maka kode tersebut otomatis akan hilang lagi. Tapi biasanya akan ada perbaikan dari sisi pengembang library-nya juga, sehingga kedepannya jika melakukan update mestinya tidak akan masalah.

**Comment by ngekoding** [comment]
Bagi yang mengalami masalah yang sama dan ingin memantau perkembangan solusinya silakan bisa cek di link berikut ini https://github.com/pedroslopez/whatsapp-web.js/issues/1569

**Comment by jamielcs** [comment]
siap pak .... saya baca dulu ....terimakasih sebelumnya
