### ISSUE TITLE
Error saat kirim pesan via postman 

### ISSUE THREAD

**Issue by jamielcs** [ngekoding/whatsapp-api-tutorial#221]
bagaimana cara mengatasi ini pak ? saya mendapatai error seperti ini saat kirim pesan 

https://prnt.sc/XeZ5Rfd1_YYT

**Comment by ngekoding** [comment]
Issue sebelumnya juga melaporkan hal yang sama, sepertinya ada masalah pada library-nya. Dicoba pastikan gunakan library versi terbaru, jalan `npm update whatsapp-web.js`

**Comment by jamielcs** [comment]
siap pak .... saya coba dulu

**Comment by jamielcs** [comment]
sudah saya coba update ... !!! dan coba scan ulang .... kasus masih sama pak ...

**Comment by ngekoding** [comment]
Bisa cek issue yang baru saja saya pin #219
