### ISSUE TITLE
/send-message eror

### ISSUE THREAD

**Issue by mecarejasa** [ngekoding/whatsapp-api-tutorial#222]
![Screen Shot 2022-07-09 at 12 22 10](https://user-images.githubusercontent.com/83715000/178092820-43843036-4cb4-4939-a404-a5c106ce8ebb.png)
#
yang mencoba tes lewat postnya untuk send message tetapi mendapatkan keterangan error seperti itu.

**Comment by Hambaini** [comment]
Iya gan saya juga demikian.itu kenapa, dari kemarin siang, mohon pencerahanya ...

**Comment by Hambaini** [comment]
e.isLid is not a function #219

Pake cara itu gan.ane ud coba

**Comment by rudipratm** [comment]
Mungkin bisa ikuti langkah saya, kemarin juga dapat kasus ini
[#216](https://github.com/ngekoding/whatsapp-api-tutorial/issues/216#issuecomment-1175727245)

**Comment by ngekoding** [comment]
Duplicate #219
