### ISSUE TITLE
Upload in hosting

### ISSUE THREAD

**Issue by ardi7923** [ngekoding/whatsapp-api-tutorial#23]
Saya coba upload d domainesia tp katanya ngak support untuk chrome puppetter bisa ngak ya kira2 d jalankan tanpa puppeter?

**Comment by ngekoding** [comment]
Tidak bisa, harus pakai Puppeteer. Mungkin bisa sewa vps saja.

**Comment by ardi7923** [comment]
saya sudah coba upload di heroku mas tapi sessionnya terhapus otomatis padahal untuk perintah disconnect sdh saya hapus jadi setiap beberapa jam harus scan barcode lagi

**Comment by poseidonwood** [comment]
case sama seperti sya , so solusi nya gmna mas ?

**Comment by ngekoding** [comment]
> saya sudah coba upload di heroku mas tapi sessionnya terhapus otomatis padahal untuk perintah disconnect sdh saya hapus jadi setiap beberapa jam harus scan barcode lagi

Coba dilihat lognya, akan lebih mudah mencari solusi jika tahu errornya.

**Comment by myhardez** [comment]
bisa pake VPS pak, agar lebih leluasa settingnya

**Comment by ngekoding** [comment]
Baik, untuk masalah ini sudah dibuatkan tutorial dan penjelasannya. Silahkan bisa dicek.

Related issue https://github.com/ngekoding/whatsapp-api-tutorial/issues/30
