### ISSUE TITLE
Cara kirim pesan dengan karakter enter

### ISSUE THREAD

**Issue by Hambaini** [ngekoding/whatsapp-api-tutorial#235]
Izin bertanya pada bapak admin  Bagaimana Cara kirim pesan dengan karakter enter,karena dengan enter tidak terkirim..mohon pencerahan

**Comment by ngekoding** [comment]
Apakah maksudnya ingin membuat baris baru?

**Comment by Hambaini** [comment]
Betul pak Muhammad.tolog pencerahnya.terima kasih

**Comment by ngekoding** [comment]
Bisa gunakan \n. Lihat contoh berikut:

Baris pertama\n
Baris kedua\n
Baris ketiga

**Comment by Hambaini** [comment]
Ok pak Nur, sudah bisa.terima kasih banyak ya.
