### ISSUE TITLE
recently update my whatsapp test message only working

### ISSUE THREAD

**Issue by Ranjith1022** [ngekoding/whatsapp-api-tutorial#239]
The latest version of Whatsapp in Lists was created but not received. Buttons and Media are completely not working.
Please give an updated source or solution to my query.

**Comment by ngekoding** [comment]
What version you use (regular/business)?

**Comment by ngekoding** [comment]
Please follow this PR for more info https://github.com/pedroslopez/whatsapp-web.js/pull/1636
