### ISSUE TITLE
QR Code not shown in heroku : UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by jens-zm** [ngekoding/whatsapp-api-tutorial#24]
Saya udah ngikutin tutorial dari awal mas, semua berjalan lancar di localhost, pas saya diploy ke heroku aplikasinya langsung berjalan gk kayak di tutorial mas, cuma qr code nya gak tampil hanya ada log menyambungkan (connecting..),..
![image](https://user-images.githubusercontent.com/78625555/107127657-24903a80-68ea-11eb-80a4-0df3265453ca.png)

Saya sudah tambah buildpack sprti di tutorial, mas masih gak bisa,
penasaran saya pake repo ini jga masih errornya sama...

saat di cek console di heroku nya ada pesan gini mas

`Aplikasi Berjalan di port :16475
(node:21) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/app/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory`

`TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md`

    at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

`(Use `node --trace-warnings ...` to show where the warning was created)
(node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate `

Sya udah coba beberapa saran yg ada, gak terselesaikan, bahasa dan pemahaman saya gak nyampe mas.. :D 

Mohon bantuannya mas

**Comment by ingGhost** [comment]
hmm iya sama nih saya juga ngalamin mas

**Comment by poseidonwood** [comment]
tambahin build packny

**Comment by ingGhost** [comment]
Sudah ditambahi mas, masih sama saja. Kira kira kenapa ya

**Comment by jens-zm** [comment]
> Saya sudah tambah buildpack sprti di tutorial, mas masih gak bisa,

Udah saya tambah, ttp gak bisa,

**Comment by ngekoding** [comment]
Halo, terima kasih atas laporannya.

Setelah saya coba langsung dengan kode dari repo ini, ternyata mendapat masalah yang sama dengan yang disebutkan di atas. Hanya saja informasi error yang disertakan kurang detail, karena setelah mendapat detail errornya kita bisa terarah untuk mencari solusi.

**Informasi Kesalahan**
```
(node:21) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/app/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

```
Masalah yang terjadi adalah terdapat lib yang kurang saat melakukan instalasi Puppeteer, sehingga Puppeteer tidak dapat berjalan sebagaimana mestinya.

**Solusi**
Terdapat 2 solusi yang bisa dipakai.
1. Mengubah buildpack Puppeteer yang awalnya menggunakan Chrome menjadi Firefox
2. Menghapus cache build

Saya lebih menyarankan melakukan solusi yang kedua, karena yang pertama akan menyebabkan melebihi batas maksimal free storage dari Heroku (hasilnya lebih dari 300MB)

Referensi yang bisa dibaca terkait solusi di atas:
- https://elements.heroku.com/buildpacks/jontewks/puppeteer-heroku-buildpack
- https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

Semoga membantu.

**Comment by jens-zm** [comment]
Terima ksih mas.. Problem solved

**Comment by ngekoding** [comment]
Sama-sama.

**Comment by LuckyArd110** [comment]
Tetap tidak bisa mas
