### ISSUE TITLE
Error pada bagian send message

### ISSUE THREAD

**Issue by ekomk** [ngekoding/whatsapp-api-tutorial#241]
Saya coba menggunakan kode yang ada di file multiple-account.js dan mengikuti petunjuknya tetapi ketika dijalankan ada error pada bagian ini

const client = sessions.find(sess => sess.id == sender)?.client;
                                                                                       ^
SyntaxError: Unexpected token '.'
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1053:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1101:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:985:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m

**Comment by ngekoding** [comment]
Nampaknya masalah versi Node.js yang digunakan, coba gunakan v14.x

**Comment by ekomk** [comment]
> Nampaknya masalah versi Node.js yang digunakan, coba gunakan v14.x

Alhamdulillah. setelah update ke node v16.17.0 sudah tidak ada pesan seperti di atas, dan sudah bisa jalan.
Terima kasih pak.

**Comment by ngekoding** [comment]
Alhamdulillah, sama-sama mas.
