### ISSUE TITLE
Status Respon False

### ISSUE THREAD

**Issue by aangwie** [ngekoding/whatsapp-api-tutorial#252]
Mas Nur @ngekoding  saya coba ikuti tutor ini sudah berhasil scan dan status authenticated, tapi setelah saya coba kirim via postman dapat respon seperti ini
[<a><img src="https://iili.io/t6LKv4.md.jpg" alt="t6LKv4.md.jpg" border="0"></a>](url)
di vps ubuntu saya pake `pm2` untuk cek log'nya tapi tidak ada error, kira-kira kenapa ya?
dan unutuk versi node dan npm ini mas,

[<a href="https://freeimage.host/id"><img src="https://iili.io/t68I5X.jpg" alt="t68I5X.jpg" border="0"></a>](url)
apakah ini berpengaruh?

**Comment by aangwie** [comment]
Alhamdulillah done
Buka file `Injected.js` pada folder `whatsapp-web.js/src/util` kemudian cari baris ke 230

```
const ephemeralSettings = {
             ephemeralDuration: chat.isEphemeralSettingOn() ? chat.getEphemeralSetting() : undefined,
             ephemeralSettingTimestamp: chat.getEphemeralSettingTimestamp() || undefined,
             disappearingModeInitiator: chat.getDisappearingModeInitiator() || undefined,
};
```

ganti menjadi
```
const ephemeralSettings = {
	    ephemeralDuration: undefined,
            ephemeralSettingTimestamp: undefined,
            disappearingModeInitiator: undefined,
};
```

Kemudian pada baris ke 371 kasih stopgap seperti ini

```
//msg.links = (message.getLinks()).map(link => ({
        //    link: link.href,
        //    isSuspicious: Boolean(link.suspiciousCharacters && link.suspiciousCharacters.size)
        //}));
```
Alhamdulillah berhasil
[Sumber ](https://github.com/pedroslopez/whatsapp-web.js/issues/1741)

**Comment by ngekoding** [comment]
Mantaps, terima kasih infonya.

**Comment by aangwie** [comment]
> Mantaps, terima kasih infonya.

Sama-sama mas... semoga bisa bermanfaat untuk yang lain...

**Comment by lurahxp** [comment]
> Alhamdulillah done Buka file `Injected.js` pada folder `whatsapp-web.js/src/util` kemudian cari baris ke 230
> 
> ```
> const ephemeralSettings = {
>              ephemeralDuration: chat.isEphemeralSettingOn() ? chat.getEphemeralSetting() : undefined,
>              ephemeralSettingTimestamp: chat.getEphemeralSettingTimestamp() || undefined,
>              disappearingModeInitiator: chat.getDisappearingModeInitiator() || undefined,
> };
> ```
> 
> ganti menjadi
> 
> ```
> const ephemeralSettings = {
> 	    ephemeralDuration: chat.ephemeralDuration,
>             ephemeralSettingTimestamp: chat.ephemeralSettingTimestamp,
>             disappearingModeInitiator: chat.disappearingModeInitiator,
> };
> ```
> 
> Kemudian pada baris ke 371 ubah bagian ini `msg.links = (message.getLinks())` menjadi `msg.links = (message._links)`
> 
> ```
>        msg.links = (message._links).map(link => ({
>             link: link.href,
>             isSuspicious: Boolean(link.suspiciousCharacters && link.suspiciousCharacters.size)
>         }));
> ```
> 
> Alhamdulillah berhasil [Sumber1](https://github.com/pedroslopez/whatsapp-web.js/issues/1741) [Sumber2](https://github.com/pedroslopez/whatsapp-web.js/compare/main...Julzk:whatsapp-web.js:main)

tx. worked
