### ISSUE TITLE
chat.isEphemeralSettingOn is not a function

### ISSUE THREAD

**Issue by Camiloignaval** [ngekoding/whatsapp-api-tutorial#253]
Please help, I'm having an error when I try to send messages, it connects without problems but the send messages endpoint throws error TypeError: chat.isEphemeralSettingOn is not a function, thank you very much any help @

**Comment by aangwie** [comment]
> Please help, I'm having an error when I try to send messages, it connects without problems but the send messages endpoint throws error TypeError: chat.isEphemeralSettingOn is not a function, thank you very much any help @

[Check Here](https://github.com/ngekoding/whatsapp-api-tutorial/issues/252#issuecomment-1286306835)  I think we have the same problem

**Comment by Camiloignaval** [comment]
Finally This problem was solved in v1.18.0!

**Comment by lurahxp** [comment]
tx. worked
