### ISSUE TITLE
API tidak berfungsi?

### ISSUE THREAD

**Issue by frozenade** [ngekoding/whatsapp-api-tutorial#255]
Hi mas

Saya coba POST sesuai di tutorial:
http://localhost:8000/send-message?number=628535059xxxx&message=test

tapi hasilnya kok muncul seperti ini ya:
```
{
    "status": false,
    "message": {
        "number": "Invalid value",
        "message": "Invalid value"
    }
}
```

Thanks in advance

**Comment by ngekoding** [comment]
Gunakapan POST Body, bukan GET Parameter.
