### ISSUE TITLE
Sudah terscan tapi tidak authenticated , tetap connecting

### ISSUE THREAD

**Issue by natsirasrafi** [ngekoding/whatsapp-api-tutorial#258]
![Screen Shot 2022-11-12 at 15 01 15](https://user-images.githubusercontent.com/15030656/201464812-65e41b71-5fb8-4780-a3dc-7a3dced308ef.png)

baru siang ini seperti itu padahal biasanya lancar

**Comment by andriefasa** [comment]
senasib, sudah tau problemnya dimana?

**Comment by andriefasa** [comment]
https://github.com/pedroslopez/whatsapp-web.js/issues/1786#issuecomment-1311578102

**Comment by andriefasa** [comment]
![image](https://user-images.githubusercontent.com/49757083/201466758-927a9a7b-321e-4a39-bad5-80cc04bd2f11.png)

**Comment by nuz-faiz** [comment]
> [pedroslopez/whatsapp-web.js#1786 (comment)](https://github.com/pedroslopez/whatsapp-web.js/issues/1786#issuecomment-1311578102)

sdh saya coba tapi tidak berhasil

**Comment by andriefasa** [comment]
![image](https://user-images.githubusercontent.com/49757083/201467966-49a4e2b4-d342-467e-8ab2-ab546cbbe5ff.png)
 berhasil ko, coba ci cek lagi di stop dulu app nya

**Comment by andriefasa** [comment]
![image](https://user-images.githubusercontent.com/49757083/201468101-db6ffe48-724f-4f77-85e5-37cec563ade9.png)

**Comment by nuz-faiz** [comment]
selain merubah 
window.Store.GroupMetadata = window.mR.findModule((module) => module.default && module.default.handlePendingInvite)[0].default;


apakah ada perubahan yang lain?

**Comment by nuz-faiz** [comment]
> ![image](https://user-images.githubusercontent.com/49757083/201468101-db6ffe48-724f-4f77-85e5-37cec563ade9.png)

terimakasih,
sdh berhasil

**Comment by andrioke** [comment]
aku jga punya masalah ini.... td siang tiba2 tidak bisa autenticated setalha scan qrcode.... tolong soluisnya apa ? Please help me...karena senin mau dipakai?

**Comment by andrioke** [comment]
thanks ....sudah berhasil.... Terima kasih ilmunya...

**Comment by natsirasrafi** [comment]
maaf lokasinya dimana ya?

**Comment by nuz-faiz** [comment]
> maaf lokasinya dimana ya?

File :
Injected.js

Folder:
node_modules/whatsapp-web.js/src/util/Injected.js

**Comment by josephvoxone** [comment]
cara merubahnya di heroku gimana ya ?

**Comment by andrioke** [comment]
> > maaf lokasinya dimana ya?
> 
> File : Injected.js
> 
> Folder: node_modules/whatsapp-web.js/src/util/Injected.js
JOGJA....
