### ISSUE TITLE
kirim media ke grup via api

### ISSUE THREAD

**Issue by diazzaid** [ngekoding/whatsapp-api-tutorial#265]
hallo..
saya ingin menanyakan cara untuk kirim gambar menggunakan api .

terima kasih

**Comment by ngekoding** [comment]
Sudah pernah dibahas, silakan merujuk pada tutorial ini [Sending Media File](https://youtu.be/ksVBXF-6Jtc)

**Comment by diazzaid** [comment]
> Sudah pernah dibahas, silakan merujuk pada tutorial ini [Sending Media File](https://youtu.be/ksVBXF-6Jtc)

ngirim nya ke grup mas bukan ke personal

**Comment by ngekoding** [comment]
Sama saja, konsepnya adalah gunakan chatId sebagai nomor tujuan.

Lihat contoh pada mengirim pesan ke grup.
