### ISSUE TITLE
NODEMON — app crashed — waiting for file changes before starting

### ISSUE THREAD

**Issue by Riyan41** [ngekoding/whatsapp-api-tutorial#270]
di linux ada kesalahan saat memulai server nodemon, Anda mungkin menghadapi kesalahan ini. Jadi, apa ini ? dan Bagaimana solusinya?

**Comment by ngekoding** [comment]
Sertakan pesan error agar lebih mudah dicari solusinya.

**Comment by Riyan41** [comment]
Error: Failed to launch the browser process!
/home/admin/wa/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

**Comment by Riyan41** [comment]
sudo npm install --location=global
