### ISSUE TITLE
Multi Wa

### ISSUE THREAD

**Issue by wulandrima1** [ngekoding/whatsapp-api-tutorial#3]
om mau tanya, kalo untuk multi , gimana?
maksudnya bikin lebih dari 1 wa, dalam 1 call node

ex. 
- Node Api.js / PM2 Start Api.js
- Open Browser

http://localhost:3000/connect/wa1, (login QRCode nomor 6281271727374)
http://localhost:3000/connect/wa2, (login QRCode nomor 6285661626364)
http://localhost:3000/connect/wa3, (login QRCode nomor 6281951235982)

jadi nanti ketika mau kirim wa, tinggal pilih..
http://localhost:3000/sendmessage/wa1/
http://localhost:3000/sendmessage/wa2/
http://localhost:3000/sendmessage/wa3/

bisa dibantu om?

**Comment by ngekoding** [comment]
Tinggal membuat instance Client untuk tiap nomor WA yang dikehendaki.

Dan silahkan sesuaikan juga pada bagian route-nya, untuk hal ini pelajari tentang route Express.js.

**Comment by MuhShalah007** [comment]
Maaf, sya baru baru2 ini belajar node.js hanya untuk buat rest api whatsapp,
adakah contoh pembuatan instance Client dan penggunannya di setiap client tersebut 

-terimakasih

**Comment by ngekoding** [comment]
Lebih jelasnya bisa merujuk ke pembahasan berikut ini:

https://github.com/pedroslopez/whatsapp-web.js/issues/45

**Comment by ngekoding** [comment]
Saya sudah membuat 2 tutorial untuk pembahasan ini, silahkan bisa disimak.
