### ISSUE TITLE
Session failed on Heroku

### ISSUE THREAD

**Issue by ipang-dwi** [ngekoding/whatsapp-api-tutorial#30]
I was deploy it on heroku, run flawlesly.. But it can't save session. Every times, I must rescan the QR Code, just for access it.. Can you explain, how about to fixing it?? I 'll waiting for your reply.. Thanks..

**Comment by rkanani108** [comment]
I am facing same issue.  Lets know fixes if anyone having.

**Comment by ipang-dwi** [comment]
@rkanani108 I wa waiting for 12 days, but never got response from @ngekoding or others..

**Comment by ngekoding** [comment]
Sorry, I think I missed reading this issue.
Maybe I need to make some test first to know the problem, maybe this caused by whatsapp update.

Please, keep this issue open.

**Comment by ipang-dwi** [comment]
@ngekoding ok, nice to hear that.. I will waiting for it..

**Comment by ngekoding** [comment]
Hi, finally I found the problem.
The point is that we can't write a file to Heroku's filesystem (ref: https://stackoverflow.com/questions/56157723/files-dont-by-fs-writefile-on-heroku)

So, the solution is we can use another way to save the session, e.g. with Mysql database.

I have a plan to make another branch for Heroku using PostgresSQL to saving the session. 
You can wait for me to do this, or  you can do it with your self now.

**Comment by ipang-dwi** [comment]
@ngekoding and @rkanani108, I think we can use Heroku config variable to save our session, but it must do manually like @ameybhavsar24 do.. check this out : https://github.com/ameybhavsar24/ww-bot/blob/master/DEPLOY.md

**Comment by ngekoding** [comment]
@ipang-dwi yes you right, I was read that also. 
But for the production purpose, I think that is not good choice, our client may not familiar about that (with no coding background).

**Comment by ipang-dwi** [comment]
@ngekoding yes bro, you are right about that..

**Comment by ameybhavsar24** [comment]
@ipang-dwi Hello
>Heroku has an “ephemeral” hard drive, this means that you can write files to disk, but those files will not persist after the application is restarted
To persist the session, I copied the session object from logs and set it as an environment variable on Heroku Dashboard. Ofcourse, it won't be possible in a production environment where the client isn't familiar with it.

**Comment by ipang-dwi** [comment]
yes brother @ameybhavsar24, I agree with you.. just using it in dev mode, so I didn't must relogin everytime wanna to using it.. for @ngekoding, I think we have clear about it and can closed this issue.. btw thanks a lot for all comments..

**Comment by creuza** [comment]
> Olá, finalmente encontrei o problema.
> A questão é que não podemos gravar um arquivo no sistema de arquivos do Heroku (ref: https://stackoverflow.com/questions/56157723/files-dont-by-fs-writefile-on-heroku )
> 
> Portanto, a solução é que podemos usar outra forma de salvar a sessão, por exemplo, com o banco de dados Mysql.
> 
> Tenho um plano de fazer outro branch para o Heroku usando PostgreSQL para salvar a sessão.
> Você pode esperar que eu faça isso, ou você pode fazer isso sozinho agora.

Como posso implementar isso?
