### ISSUE TITLE
command line error : Express-file-upload: Request is not eligible for file upload!

### ISSUE THREAD

**Issue by mzayn** [ngekoding/whatsapp-api-tutorial#31]
gimana mau fix error 

![image](https://user-images.githubusercontent.com/15009301/108644164-e0f02000-74e8-11eb-82fb-a4def58c7a0b.png)

reserve proxy dah enable di apache. run like normally. 

jadinya lepas update & upgrade npm update via terminal. 

gimana mau fix?

**Comment by ngekoding** [comment]
Sudah coba kirim file?

**Comment by mzayn** [comment]
solved problem..

**Comment by mzayn** [comment]
sekarang gimana mau buat 

2 server dan 2 domain yang berbeda.. 

--- 
contoh.. 

1 domain server khas untuk node.js running.. 
dan
1 domain untuk host html aja. 

-----

berikut code saya sudah edit betul ngak? 

-

```
const SESSION_FILE_PATH = './data1/whatsapp-session.json';
let sessionCfg;
if (fs.existsSync(SESSION_FILE_PATH)) {
  sessionCfg = require(SESSION_FILE_PATH);
}

app.get('/', (req, res) => {
  res.sendFile('domain2.xyz/index.html', {
    root: __dirname
  });
});
```

setting req and res file get ke server domain 2..

**Comment by ngekoding** [comment]
Satu issue untuk satu topik saja, silahkan buat issue baru.

**Comment by yaza-putu** [comment]
> solved problem..

apa solusinya bang..?
