### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined 

### ISSUE THREAD

**Issue by yan043** [ngekoding/whatsapp-api-tutorial#32]
![image](https://user-images.githubusercontent.com/62176525/108680039-4dd6da80-7528-11eb-9ba0-cdcef523eb1b.png)

mohon bantuannya mas, terimakasih

`app.post('/send-media', async (req, res) => {
	const number = phoneNumberFormatter(req.body.number);
	const caption = req.body.caption;
	const fileUrl = req.body.file;
	
	// const media = MessageMedia.fromFilePath('./image-example.png');
	// const file = req.files.file;
	// const media = new MessageMedia(file.mimetype, file.data.toString('base64'), file.name);

	let mimetype;
	const attachment = await axios.get(fileUrl, { responseType: 'arraybuffer' }).then(response => {
		mimetype = response.headers['contente-type'];
		return response.data.toString('base64');
	});

	const media = new MessageMedia(mimetype, attachment, 'Media');

	client.sendMessage(number, media, { caption: caption }).then(response => {
		res.status(200).json({
			status: true,
			response: response
		});
	}).catch(err => {
		res.status(500).json({
			status: false,
			response: err
		});
	});
});`

**Comment by ngekoding** [comment]
Variabel `number` belum ada. Pastikan saat mengirim request sudah menyertakan data yang diperlukan, silahkan lihat pada tutorial menambah validasi untuk menambah error handler.

**Comment by yan043** [comment]
sudah bisa mas alhamdulillah post nya x-www-form-url-encoded, tapi sisa 1 pesan

Express-file-upload: Request is not eligible for file upload

**Comment by ngekoding** [comment]
Silahkan dicoba mengirim pesan media dengan uploaf file.
Untuk menghilangkan pesan itu, ubah pengaturan fileUpload debug menjadi FALSE.
