### ISSUE TITLE
sh: nodemon: command not found di hosting node js

### ISSUE THREAD

**Issue by natsirasrafi** [ngekoding/whatsapp-api-tutorial#33]
returncode: 1
stdout:
> whatsapp-api@1.0.0 start:dev /home/akunhosting/wa
> nodemon app.js
stderr:
npm WARN lifecycle The node binary used for scripts is /home/akunhosting/nodevenv/wa/10/bin/node but npm is using /opt/alt/alt-nodejs10/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
sh: nodemon: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! whatsapp-api@1.0.0 start:dev: `nodemon app.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the whatsapp-api@1.0.0 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/akunhosting/.npm/_logs/2021-02-23T02_16_12_178Z-debug.log

**Comment by natsirasrafi** [comment]
complete log 

0 info it worked if it ends with ok
1 verbose cli [ '/opt/alt/alt-nodejs10/root/usr/bin/node',
1 verbose cli   '/opt/alt/alt-nodejs10/root/usr/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'start:dev',
1 verbose cli   '--' ]
2 info using npm@6.14.6
3 info using node@v10.22.0
4 verbose run-script [ 'prestart:dev', 'start:dev', 'poststart:dev' ]
5 info lifecycle whatsapp-api@1.0.0~prestart:dev: whatsapp-api@1.0.0
6 info lifecycle whatsapp-api@1.0.0~start:dev: whatsapp-api@1.0.0
7 warn lifecycle The node binary used for scripts is /home/satoeind/nodevenv/wa/10/bin/node but npm is using /opt/alt/alt-nodejs10/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
8 verbose lifecycle whatsapp-api@1.0.0~start:dev: unsafe-perm in lifecycle true
9 verbose lifecycle whatsapp-api@1.0.0~start:dev: PATH: /opt/alt/alt-nodejs10/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/node-gyp-bin:/home/satoeind/wa/node_modules/.bin:/home/satoeind/nodevenv/wa/10/bin:/opt/alt/alt-nodejs10/root/usr/bin:/home/satoeind/nodevenv/wa/10/lib/bin/:/usr/local/jdk/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin:/opt/bin
10 verbose lifecycle whatsapp-api@1.0.0~start:dev: CWD: /home/satoeind/wa
11 silly lifecycle whatsapp-api@1.0.0~start:dev: Args: [ '-c', 'nodemon app.js' ]
12 info lifecycle whatsapp-api@1.0.0~start:dev: Failed to exec start:dev script
13 verbose stack Error: whatsapp-api@1.0.0 start:dev: `nodemon app.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/opt/alt/alt-nodejs10/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:48:18)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid whatsapp-api@1.0.0
15 verbose cwd /home/satoeind/wa
16 verbose Linux 3.10.0-962.3.2.lve1.5.38.el7.x86_64
17 verbose argv "/opt/alt/alt-nodejs10/root/usr/bin/node" "/opt/alt/alt-nodejs10/root/usr/bin/npm" "run-script" "start:dev" "--"
18 verbose node v10.22.0
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error syscall spawn
22 error file sh
23 error errno ENOENT
24 error whatsapp-api@1.0.0 start:dev: `nodemon app.js`
24 error spawn ENOENT
25 error Failed at the whatsapp-api@1.0.0 start:dev script.
25 error This is probably not a problem with npm. There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by ngekoding** [comment]
Library `nodemon` belum diinstall.

**Comment by Collins77** [comment]
How did you fix this?
