### ISSUE TITLE
cara code untuk    if (msg.body == '!ping')  - untuk uppercase, lowecase and etc

### ISSUE THREAD

**Issue by mzayn** [ngekoding/whatsapp-api-tutorial#34]
bro, 

gimana mau buat jika kita hantar uppercase, lowercase, and etc senteces upperlowercase... and server bisa hantar reply balik. unutk codenya.. 

client.on('message', msg => {
  if (msg.body == '!ping') {
    msg.reply('pong');

masih cari cara mau edit. banyak yang jumpa untuk php bisa.

**Comment by ngekoding** [comment]
Tinggal dijadikan lowercase saja msg.body-nya, kemudian dibandingkan dengan yang sama-sama lowercase. Berikut contohnya:

```
if (msg.body.toLowerCase() == '!ping') {
// do something
}
```
Sehingga, walaupun yang dikirim !PING atau !pIng atau !Ping akan sama saja.

**Comment by mzayn** [comment]
> Tinggal dijadikan lowercase saja msg.body-nya, kemudian dibandingkan dengan yang sama-sama lowercase. Berikut contohnya:
> 
> ```
> if (msg.body.toLowerCase() == '!ping') {
> // do something
> }
> ```
> 
> Sehingga, walaupun yang dikirim !PING atau !pIng atau !Ping akan sama saja.

ok noted.

jika saya send balik kat ws : `!PiNg` 
tiada reply dari client server gimana mau fix.

**Comment by mzayn** [comment]
> Tinggal dijadikan lowercase saja msg.body-nya, kemudian dibandingkan dengan yang sama-sama lowercase. Berikut contohnya:
> 
> ```
> if (msg.body.toLowerCase() == '!ping') {
> // do something
> }
> ```
> 
> Sehingga, walaupun yang dikirim !PING atau !pIng atau !Ping akan sama saja.

solved. 

kalau gimana mau client reply + mention user.. code ini betul ? 

```
client.on('message', async (msg) => {

    const user = await msg.getContact();

   if (msg.body.toLowerCase() == '!ping') {
    msg.reply('pong');

  } else if (msg.body.toLowerCase() == "hi") {
    msg.reply(Hello @${user.id.user}, {
        mentions: [user]
    });
```
