### ISSUE TITLE
throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));

### ISSUE THREAD

**Issue by yan043** [ngekoding/whatsapp-api-tutorial#35]
![image](https://user-images.githubusercontent.com/62176525/109098912-24eb5b00-775d-11eb-85b0-bd1c25c0eae5.png)

kemaren masih normal mas, pas udah cek pagi ini ada pesan error sehabis di scan qrcode . Mohon bantuannya mas

**Comment by yogisupra88** [comment]
di Upgrade lagi aja bro.. ke whatsapp-web.js versi 1.12.5

**Comment by yan043** [comment]
udah solved itu mas di update tapi ada error baru lagi cmiiw

![image](https://user-images.githubusercontent.com/62176525/109120546-0eef9180-7781-11eb-9d5a-547350b42c1d.png)

**Comment by yan043** [comment]
> udah solved itu mas di update tapi ada error baru lagi cmiiw
> 
> ![image](https://user-images.githubusercontent.com/62176525/109120546-0eef9180-7781-11eb-9d5a-547350b42c1d.png)

next issue aja lah hehe

**Comment by mamoru-69** [comment]
Wa js saya ver ^1.15.3
tapi masi sama gitu

**Comment by aldiandika** [comment]
Ada perkembangan ? dengan issue ini ?
WA Js saya ver 1.15.3, tapi masih sama error nya

**Comment by marwandhiaurrahman** [comment]
Kasus ini terjadi pada saya saat clien belum ready , tetapi kita sudah melakukan perintah mengirim pesan, maka timbullah error ini

**Comment by faliqali** [comment]
cara antisipasinya gmn ya, mungkin biar auto start lg gtomm. atau skip eror nya?
