### ISSUE TITLE
Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary

### ISSUE THREAD

**Issue by yan043** [ngekoding/whatsapp-api-tutorial#36]
![image](https://user-images.githubusercontent.com/62176525/109133305-d5725280-778f-11eb-9a71-f114d56163ed.png)

assalamuallaikum mas mohon bantuan nya :)

sudah coba install firefox sama puppeteer-firefox tetap gabisa

**Comment by yogisupra88** [comment]
https://github.com/pedroslopez/whatsapp-web.js/issues/567

**Comment by ngekoding** [comment]
Wa'alaikumussalam

Sudah coba jalankan `npm update`?

**Comment by yan043** [comment]
udah solved mas lupa ngabari hehe, makasih banyak berkah berkah
