### ISSUE TITLE
Bagaimana cara if (msg.body == '!ping') di app-multiple-device kak?

### ISSUE THREAD

**Issue by brian720hz** [ngekoding/whatsapp-api-tutorial#37]
saya sudah coba yang app-multiple-device dan bisa. saya ingin tau cara menerima pesan di multiple device sesuai season dan dan memsakukan data yg diterima ke database. mohon dibantu

terima kasih

**Comment by ngekoding** [comment]
Caranya sama dengan yang biasa, tinggal tambah `client.on('message'...)` seperti biasa. Mirip saat membuat on qr.

**Comment by brian720hz** [comment]
bisa minta source codenya untuk if (msg.body == '!ping') di app-multiple-device kak? soalnya sudah saya coba2 tapi tidak work
