### ISSUE TITLE
gimana mau keep alive - server untuk auto reply

### ISSUE THREAD

**Issue by mzayn** [ngekoding/whatsapp-api-tutorial#39]
salam, 

gimana mau setting app.js untuk keep alive auto reply whatapp bot ? 

sebab dalam beberapa jam nodemon running ok untuk whatapp API. but untuk auto reply dia terus OFF bila buat !ping ke ws bot.. bot tidak reply. 

cara mau fix gimana?

**Comment by ngekoding** [comment]
Selain itu, penggunaan nodemon biasanya saat development saja, adapun jika production menggunakan pm2.

**Comment by mzayn** [comment]
> Sudah dicek apakah ada error?

tiada errornya.. just untuk bot auto reply tidak function. maybe sebabnya pengunaan nodemon 24/h.. utk api production ok sahaja.



> Selain itu, penggunaan nodemon biasanya saat development saja, adapun jika production menggunakan pm2.

ada tutorial gimana mau setting pm2 ? replace nodemon ya

**Comment by ngekoding** [comment]
Seharusnya tidak masalah jika untuk kirim pesan bisa. 
Boleh sertakan kode yang digunakan?

Untuk penggunaan pm2 bisa baca disini https://pm2.keymetrics.io

**Comment by mzayn** [comment]
> Seharusnya tidak masalah jika untuk kirim pesan bisa.
> Boleh sertakan kode yang digunakan?
> 
> Untuk penggunaan pm2 bisa baca disini https://pm2.keymetrics.io

untuk codenya 

```
const client = new Client({
    keepAlive: true, 
    authTimeoutMs: 45000,
    qrRefreshIntervalms: 5000,
   restartOnAuthFail: true,
    takeoverTimeoutMs: 100,
    takeoverOnConflict: true,
    
  puppeteer: {
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-accelerated-2d-canvas',
      '--no-first-run',
      '--no-zygote',
      '--single-process', // <- this one doesn't works in Windows
      '--disable-gpu'
    ],
  },
  session: sessionCfg
});


client.on('message', async msg => { 
    client.sendPresenceAvailable()
let chat = await msg.getChat()
const contact = await msg.getContact()

   if (msg.body.toLowerCase() == '!ping' && !chat.isGroup) {
    msg.reply('pong');
  }
  
  else if (msg.body.toLowerCase() == 'good morning' && !chat.isGroup) {
    msg.reply('selamat pagi');
    
 } else if (msg.body.toLowerCase() == 'hi' && !chat.isGroup) {
    msg.reply('Hi ?');
    
    
  } else if (msg.body == '!groups') {
    client.getChats().then(chats => {
      const groups = chats.filter(chat => chat.isGroup);

      if (groups.length == 0) {
        msg.reply('You have no group yet.');
      } else {
        let replyMsg = '*YOUR GROUPS*\n\n';
        groups.forEach((group, i) => {
          replyMsg += `ID: ${group.id._serialized}\nName: ${group.name}\n\n`;
        });
        replyMsg += '_You can use the group id to send a message to the group._'
        msg.reply(replyMsg);
      }
    });
  }
});
```

code masih sama yang asli. just ubah untuk kept alive server di const client = new Client ... fail gak. 

lebih dari 3-7/hour ... auto bot fail to reply again. 

tapi send via API bisa masuk message. 

--------

untuk pm2 masih kurang jelas configure untuk whatapp-api

**Comment by brian720hz** [comment]
sama yg auto bot untuk multiple device ga work. ada yg bisa bantu?

**Comment by ngekoding** [comment]
Apakah menggunakan Heroku?

**Comment by mzayn** [comment]
> Apakah menggunakan Heroku?

guna vps + nodejs + apache

**Comment by ngekoding** [comment]
Seharusnya tidak masalah jika untuk kirim pesan berhasil.
Coba jalankan dengan `pm2 start app.js --name "whatsapp-api"`

**Comment by mzayn** [comment]
> Seharusnya tidak masalah jika untuk kirim pesan berhasil.
> Coba jalankan dengan `pm2 start app.js --name "whatsapp-api"`

success add. 
pm2 running..

tapi bila runningnya pm2 + nodemon server jadi overload..

saya punya spec server 

2core, 2cpu, 2thread = 90% usage.. 
Running blocked = 100% load.

**Comment by ngekoding** [comment]
Nodemon tidak diperlukan saat sudah pakai pm2

**Comment by mzayn** [comment]
> Nodemon tidak diperlukan saat sudah pakai pm2

kiranya start node app.js sahaja bila mau run + pm2 ..

sebabnya jika run pm2 app.js - whatapps bot tidak running bila send !ping di whatapps ; bot tidak reply

**Comment by mzayn** [comment]
satu lagi ya.. 

bila save edit code di app.js - pm2 tidak auto restart .. refresh bagi module baru.. ada cara lain bagi pm2 buat auto restart bila kita selesai save code baru di app.js

thanks

**Comment by ngekoding** [comment]
pm2 memang diperuntukkan untuk penggunaan production, sehingga apabila ada perubahan kode perlu untuk run ulang. Silahkan dipelajari lebih detail mengenai penggunaan pm2.

Jika masih tahap development, maka gunakan nodemon.

**Comment by mzayn** [comment]
> pm2 memang diperuntukkan untuk penggunaan production, sehingga apabila ada perubahan kode perlu untuk run ulang. Silahkan dipelajari lebih detail mengenai penggunaan pm2.
> 
> Jika masih tahap development, maka gunakan nodemon.

ok noted. 

------

tapi auto bot reply masih sama.... not running when active for 3-8 hour - pm2 start  ( auto reply bot  not reply message )

bila check di server tiada error log.
