### ISSUE TITLE
publish docker azure

### ISSUE THREAD

**Issue by QuelitonSouza** [ngekoding/whatsapp-api-tutorial#4]
Hi,

I thought the project was really cool and I broke my head a little to get it published on azure.
I will leave it here so I can publish the application in azure.

[How to create Docker](https://medium.com/dockerbr/publicando-imagem-docker-no-azure-web-app-for-containers-em-7-passos-d2a0be4fc4d3)

# Commands
## step 1

    docker build -t "[user docker hub]/[name your project]" -f "Dockerfile" "."

  ## step 2
  
    docker login

   ## step 3
  
    docker push "[user docker hub]/[name your project]"

## DockerFile

    FROM node:12-slim
    
    RUN apt-get update \
        && apt-get install -y wget gnupg \
        && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
        && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
        && apt-get update \
        && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
          --no-install-recommends \
        && rm -rf /var/lib/apt/lists/*
    
    RUN npm i puppeteer \
        && groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
        && mkdir -p /home/pptruser/Downloads \
        && chown -R pptruser:pptruser /home/pptruser \
        && chown -R pptruser:pptruser /node_modules
    
    
    WORKDIR /app
    COPY package*.json ./
    
    RUN npm install
    RUN npm i -g nodemon
    
    COPY . .
    
    EXPOSE 80
    CMD ["nodemon","app.js"]

# attention

## File Index.hml
change the port from 8000 to 80
in the index.html file the line
var socket = io.connect ('http: // localhost: 8000', {path: '/socket.io'});
switch to
var socket = io.connect ('your azure url', {path: '/socket.io'});

## app.js
at the end of the app.js file, change port line
in
server.listen (8000, function () {
for
server.listen (80, function () {

**Comment by dulumina** [comment]
saya coba pakai dockerfile ini dan menjalankan di docker windows tidak bisa;
errornya seperti ini :

```
const client = sessions.find((sess) => sess.id == sender)?.client;
                                                                                           ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by ngekoding** [comment]
> saya coba pakai dockerfile ini dan menjalankan di docker windows tidak bisa; errornya seperti ini :
> 
> ```
> const client = sessions.find((sess) => sess.id == sender)?.client;
>                                                             ^
> 
> SyntaxError: Unexpected token '.'
>     at wrapSafe (internal/modules/cjs/loader.js:915:16)
>     at Module._compile (internal/modules/cjs/loader.js:963:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
>     at internal/main/run_main_module.js:17:47
> ```

Nampaknya masalah di versi Node.js, coba gunakan versi 14.x
