### ISSUE TITLE
Bagaimana membuat custom onMessage ambil data dari table di database sesuai msg.body

### ISSUE THREAD

**Issue by kakzi** [ngekoding/whatsapp-api-tutorial#40]
saya mau nanya pak. implementasi custom onMessage ambil data dari table di database sesuai msg.body gimna ya pak
ini get data dari table 

const mysql = require('mysql');

const connection = mysql.createConnection({
  host: 'localhost',
  user: 'root',
  password: '',
  database: 'testdb'
});
connection.connect((err) => {
  if (err) throw err;
  console.log('Connected!');
});

connection.query('SELECT * FROM bot', (err,rows) => {
    if(err) throw err;
  
    console.log('Data received from Db:');
    console.log(rows);
  });

kemudian saya mencoba dengan code seperti ini tapi response balasan dari WA ndak ada..
berikut kodenya pak.... maaf,, masih belajar 

client.on('message', msg => {
    rows.forEach( (row) => {
        if(row.msg == '!ping'){
            msg.reply(`${row.reply}`);
        }
    });
    // if (msg.body == '!ping') {
    //     msg.reply('pong');
    // } else if(msg.body == 'good morning'){
    //     msg.reply('selamat pagi')
    // }
});

strukture table seperti ini pak :
kode INT(11)
msg VARCHAR(256)
replay (TEXT)

berikut kode utuhnya pak :
const { Client } = require('whatsapp-web.js');
const qrcode = require('qrcode-terminal');
const fs = require('fs');
const mysql = require('mysql');

const connection = mysql.createConnection({
  host: 'localhost',
  user: 'root',
  password: '',
  database: 'testdb'
});
connection.connect((err) => {
  if (err) throw err;
  console.log('Connected!');
});

connection.query('SELECT * FROM bot', (err,rows) => {
    if(err) throw err;
  
    console.log('Data received from Db:');
    console.log(rows);
  });

const SESSION_FILE_PATH = './whatsapp-session.json';
let sessionCfg;
if (fs.existsSync(SESSION_FILE_PATH)) {
    sessionCfg = require(SESSION_FILE_PATH);
}

const client = new Client({ puppeteer: { headless: true }, session: sessionCfg });

client.on('qr', (qr) => {
    // Generate and scan this code with your phone
    console.log('QR RECEIVED', qr);
    qrcode.generate(qr);
});

client.on('authenticated', (session) => {
    console.log('AUTHENTICATED', session);
    sessionCfg=session;
    fs.writeFile(SESSION_FILE_PATH, JSON.stringify(session), function (err) {
        if (err) {
            console.error(err);
        }
    });
});

client.on('ready', () => {
    console.log('Client is ready!');
});

client.on('message', msg => {
    rows.forEach( (row) => {
        if(row.msg == '!ping'){
            msg.reply(`${row.reply}`);
        }
    });
    // if (msg.body == '!ping') {
    //     msg.reply('pong');
    // } else if(msg.body == 'good morning'){
    //     msg.reply('selamat pagi')
    // }
});

client.initialize();

**Comment by ngekoding** [comment]
Silahkan diperbaiki dulu pertanyaannya agar lebih mudah dibaca. 
Bisa gunakan fungsi insert code agar lebih rapi.

**Comment by mzayn** [comment]
> saya mau nanya pak. implementasi custom onMessage ambil data dari table di database sesuai msg.body gimna ya pak
> ini get data dari table
> 
> const mysql = require('mysql');
> 
> const connection = mysql.createConnection({
> host: 'localhost',
> user: 'root',
> password: '',
> database: 'testdb'
> });
> connection.connect((err) => {
> if (err) throw err;
> console.log('Connected!');
> });
> 
> connection.query('SELECT * FROM bot', (err,rows) => {
> if(err) throw err;
> 
> ```
> console.log('Data received from Db:');
> console.log(rows);
> ```
> 
> });
> 
> kemudian saya mencoba dengan code seperti ini tapi response balasan dari WA ndak ada..
> berikut kodenya pak.... maaf,, masih belajar
> 
> client.on('message', msg => {
> rows.forEach( (row) => {
> if(row.msg == '!ping'){
> msg.reply(`${row.reply}`);
> }
> });
> // if (msg.body == '!ping') {
> // msg.reply('pong');
> // } else if(msg.body == 'good morning'){
> // msg.reply('selamat pagi')
> // }
> });
> 
> strukture table seperti ini pak :
> kode INT(11)
> msg VARCHAR(256)
> replay (TEXT)
> 
> berikut kode utuhnya pak :
> const { Client } = require('whatsapp-web.js');
> const qrcode = require('qrcode-terminal');
> const fs = require('fs');
> const mysql = require('mysql');
> 
> const connection = mysql.createConnection({
> host: 'localhost',
> user: 'root',
> password: '',
> database: 'testdb'
> });
> connection.connect((err) => {
> if (err) throw err;
> console.log('Connected!');
> });
> 
> connection.query('SELECT * FROM bot', (err,rows) => {
> if(err) throw err;
> 
> ```
> console.log('Data received from Db:');
> console.log(rows);
> ```
> 
> });
> 
> const SESSION_FILE_PATH = './whatsapp-session.json';
> let sessionCfg;
> if (fs.existsSync(SESSION_FILE_PATH)) {
> sessionCfg = require(SESSION_FILE_PATH);
> }
> 
> const client = new Client({ puppeteer: { headless: true }, session: sessionCfg });
> 
> client.on('qr', (qr) => {
> // Generate and scan this code with your phone
> console.log('QR RECEIVED', qr);
> qrcode.generate(qr);
> });
> 
> client.on('authenticated', (session) => {
> console.log('AUTHENTICATED', session);
> sessionCfg=session;
> fs.writeFile(SESSION_FILE_PATH, JSON.stringify(session), function (err) {
> if (err) {
> console.error(err);
> }
> });
> });
> 
> client.on('ready', () => {
> console.log('Client is ready!');
> });
> 
> client.on('message', msg => {
> rows.forEach( (row) => {
> if(row.msg == '!ping'){
> msg.reply(`${row.reply}`);
> }
> });
> // if (msg.body == '!ping') {
> // msg.reply('pong');
> // } else if(msg.body == 'good morning'){
> // msg.reply('selamat pagi')
> // }
> });
> 
> client.initialize();

bole share source di github.. mau coba connect di database juga di database.. jika diberi keizinan. terima kasih.

**Comment by kakzi** [comment]
begini pak codingnya
`const { Client } = require('whatsapp-web.js');
const qrcode = require('qrcode-terminal');
const fs = require('fs');
const mysql = require('mysql');


const connection = mysql.createConnection({
  host: 'localhost',
  user: 'root',
  password: '',
  database: 'testdb'
});
connection.connect((err) => {
  if (err) throw err;
  console.log('Connected!');
});


connection.query('SELECT * FROM bot', (err,rows) => {
    if(err) throw err;

    console.log('Data received from Db:');
    console.log(rows);
});



const SESSION_FILE_PATH = './whatsapp-session.json';
let sessionCfg;
if (fs.existsSync(SESSION_FILE_PATH)) {
    sessionCfg = require(SESSION_FILE_PATH);
}

const client = new Client({ puppeteer: { headless: true }, session: sessionCfg });

client.on('qr', (qr) => {
    // Generate and scan this code with your phone
    console.log('QR RECEIVED', qr);
    qrcode.generate(qr);
});

client.on('authenticated', (session) => {
    console.log('AUTHENTICATED', session);
    sessionCfg=session;
    fs.writeFile(SESSION_FILE_PATH, JSON.stringify(session), function (err) {
        if (err) {
            console.error(err);
        }
    });
});

client.on('ready', () => {
    console.log('Client is ready!');
});

client.on('message', msg => {
    rows.forEach( (row) => {
        if(row.msg == '!ping'){
            msg.reply(`${row.reply}`);
        }
    });
});

client.initialize();`

**Comment by kakzi** [comment]
![image](https://user-images.githubusercontent.com/54353303/110937431-eeb8f880-8364-11eb-83de-9a2ffb386cfa.png)
![image](https://user-images.githubusercontent.com/54353303/110937473-fe384180-8364-11eb-8c66-7ce5c96caf08.png)

**Comment by kakzi** [comment]
terima kasih atas respons baiknya pak,, semoga sehat selalu... mhon bantuanya ya pak,, kira kira salahnya di mana jika buat custom onMessage dari table mysql....

**Comment by ngekoding** [comment]
Silahkan ikuti tutorial berikut ini https://youtu.be/iode8kstDYQ
