### ISSUE TITLE
Bug, aplikasi Whatsapp crash

### ISSUE THREAD

**Issue by belutz** [ngekoding/whatsapp-api-tutorial#41]
jika nomor tujuan tidak valid/ditemukan (ex: no tujuan cuman 0 (1 angka))  aplikasi WA di hp langsung crash
apakah ada cara untuk mengvalidasi nomor tujuan?

**Comment by ngekoding** [comment]
Silahkan ikuti tutorialnya secara perlahan dan seksama, sudah dijelaskan.
