### ISSUE TITLE
gagal install di ubuntu server 18.04

### ISSUE THREAD

**Issue by thisem** [ngekoding/whatsapp-api-tutorial#42]
> whatsapp-api@1.0.0 start /home/ubuntu/nodejs/whatsapp-api-tutorial
> node app.js

App running on *: 8000
(node:11198) UnhandledPromiseRejectionWarning: Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (/home/ubuntu/nodejs/whatsapp-api-tutorial/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:79:23)
    at async Client.initialize (/home/ubuntu/nodejs/whatsapp-api-tutorial/node_modules/whatsapp-web.js/src/Client.js:67:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ngekoding** [comment]
Ubuntu memerlukan beberapa library tambahan untuk bisa menjalankan Puppeteer.

Silahkan install terlebih dahulu.

```sh
sudo apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
```
Jika sudah, silahkan dijalankan ulang.

**Comment by thisem** [comment]
sudah diinstall lib nya mas, tapi pesan issuenya masih sama spt di atas.

Reading package lists... Done
Building dependency tree
Reading state information... Done
libatk1.0-0 is already the newest version (2.28.1-1).
libfontconfig1 is already the newest version (2.12.6-0ubuntu2).
libgdk-pixbuf2.0-0 is already the newest version (2.36.11-2).
libnspr4 is already the newest version (2:4.18-1ubuntu1).
libxcomposite1 is already the newest version (1:0.4.4-2).
libxcursor1 is already the newest version (1:1.1.15-1).
libxdamage1 is already the newest version (1:1.1.4-3).
libxext6 is already the newest version (2:1.3.3-1).
libxfixes3 is already the newest version (1:5.0.3-1).
libxi6 is already the newest version (2:1.7.9-1).
libxrandr2 is already the newest version (2:1.5.1-1).
libxrender1 is already the newest version (1:0.9.10-1).
libxss1 is already the newest version (1:1.2.2-1).
libxtst6 is already the newest version (2:1.2.3-1).
lsb-release is already the newest version (9.20170808ubuntu1).
gconf-service is already the newest version (3.2.6-4ubuntu1).
libgconf-2-4 is already the newest version (3.2.6-4ubuntu1).
ca-certificates is already the newest version (20210119~18.04.1).
fonts-liberation is already the newest version (1:1.07.4-7~18.04.1).
libasound2 is already the newest version (1.1.3-5ubuntu0.5).
libc6 is already the newest version (2.27-3ubuntu1.4).
libc6 set to manually installed.
libcairo2 is already the newest version (1.15.10-2ubuntu0.1).
libcups2 is already the newest version (2.2.7-1ubuntu2.8).
libdbus-1-3 is already the newest version (1.12.2-1ubuntu1.2).
libexpat1 is already the newest version (2.2.5-3ubuntu0.2).
libgcc1 is already the newest version (1:8.4.0-1ubuntu1~18.04).
libglib2.0-0 is already the newest version (2.56.4-0ubuntu0.18.04.8).
libgtk-3-0 is already the newest version (3.22.30-1ubuntu4).
libnss3 is already the newest version (2:3.35-2ubuntu2.12).
libpango-1.0-0 is already the newest version (1.40.14-1ubuntu0.1).
libpangocairo-1.0-0 is already the newest version (1.40.14-1ubuntu0.1).
libstdc++6 is already the newest version (8.4.0-1ubuntu1~18.04).
libx11-6 is already the newest version (2:1.6.4-3ubuntu0.3).
libx11-xcb1 is already the newest version (2:1.6.4-3ubuntu0.3).
libxcb1 is already the newest version (1.13-2~ubuntu18.04).
wget is already the newest version (1.19.4-1ubuntu2.2).
xdg-utils is already the newest version (1.1.2-1ubuntu2.5).
libappindicator1 is already the newest version (12.10.1+18.04.20200408.1-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 40 not upgraded.

**Comment by ngekoding** [comment]
Silahkan hapus folder node_modules, kemudian jalankan npm install lagi.

**Comment by ngekoding** [comment]
Dan pastikan menggunakan versi terbaru dari whatsapp-web.js

**Comment by thisem** [comment]
Thanks mas setelah hapus folder node_modules lalu npm lagi modulenya. skarang sudah bisa.
oh ya mas. script app.js nya saya ada modif untuk penggunaan webhook yang mengambil data dari halaman php di web lain dan ini juga sudah bisa bekerja.

tapi saya ingin kembangkan untuk : 
1. yang /send-message bagaimana caranya untuk meletakkan Authorization di headernya ya mas, supaya ada otorisasi saat post ke url/send-message
2. sudah dikembangkan untuk send pdf belum mas, bagaimana caranya supaya ada API lagi /send-pdf . terima kasih

**Comment by thisem** [comment]
yang case 2 closed mas, ternyata media tidak hanya berupa gambar, saya coba kirim PDF juga bisa. thanks

**Comment by ngekoding** [comment]
Setiap issue untuk satu pembahasan saja, silahkan buat issue yang lain.
