### ISSUE TITLE
Hosting in heroku

### ISSUE THREAD

**Issue by eno-erno** [ngekoding/whatsapp-api-tutorial#43]
hallo mas saya sudah mengikuti tutorial sampai seri terakhir terus hilang terimakasih saya bisa clone projectnya hehe, sekalian dong mau nanya saya coba hosting di heroku ko qrcode ga muncul yaa?? terimakasih

https://wa-nodejs-api.herokuapp.com/ hasil deploynya

**Comment by ngekoding** [comment]
Kita harus tahu dulu permasalahannya, di video "Deploy to Heroku" saya jelaskan cara liat logs untuk memudahkan.

Tapi saya berasumsi masalahnya karena cache yang ada di Heroku, jadi harus dibersihkan dulu dan lakukan deploy ulang. Silahkan baca dan ikuti ini https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

Hal lainnya, jangan lupa menambah buildpack Puppeteer.
