### ISSUE TITLE
clearMessages

### ISSUE THREAD

**Issue by riagie** [ngekoding/whatsapp-api-tutorial#44]
untuk code clearMessages pada 1 id chat bagaimana ya mas ?

**Comment by ngekoding** [comment]
Bisa gunakan ini https://pedroslopez.me/whatsapp-web.js/Chat.html#clearMessages

**Comment by riagie** [comment]
> Bisa gunakan ini https://pedroslopez.me/whatsapp-web.js/Chat.html#clearMessages

(node:124) UnhandledPromiseRejectionWarning: Error: Evaluation failed: n
at ExecutionContext._evaluateInternal (...\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async ExecutionContext.evaluate (...\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
at async Client. (...\whatsapp.js:120:17)
(node:124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

----

('/clearMessages', async (req, res) => {
const chat = await client.getChatById(number);
const clear = await chat.clearMessages();

**Comment by ngekoding** [comment]
Coba dicek, apakah proses get chat tersebut berhasil?

**Comment by riagie** [comment]
> Coba dicek, apakah proses get chat tersebut berhasil?

untuk client.getChatById(number) normal muncul data namun ketika await chat.clearMessages() mendapatkan error.

**Comment by ngekoding** [comment]
Saya tidak tahu kenapa, mungkin bisa sertakan kode lengkapnya. 
Berikut ini sudah saya tambahkan contoh clear message yang berhasil: https://github.com/ngekoding/whatsapp-api-tutorial/commit/4bfd9118fc0a0850866585e476b337e39d48095b

**Comment by ngekoding** [comment]
Coba hapus folder node_modules, dan jalankan npm install.

**Comment by riagie** [comment]
> Coba hapus folder node_modules, dan jalankan npm install.

sudah mas sya coba npm i dari awal tapi masih dapet error.
versi puppeter dan wa nya sudah sama juga

**Comment by ngekoding** [comment]
I don't know why, coba sertakan kode lengkapnya.
