### ISSUE TITLE
Dynamic Message Reply - help for fix.

### ISSUE THREAD

**Issue by mzayn** [ngekoding/whatsapp-api-tutorial#45]
salam, 

gimana mau buat jika nak bezakan db - Dynamic Message Reply untuk private message dan group message auto reply ? 
adakah guna 2 DB ? 

dan gimana kalau sebelum ini guna code di app.js  : contohnya ini

```

Code ini khas untuk Private chat ... bila coba masuk keyword ping di private chat berhasil untuk private chat.
tapi gimana mau buat untuk DB private chat seperti code dibawah ya. ? 

if (msg.body.toLowerCase().includes('ping') && !chat.isGroup) { {
    msg.reply('pong');


```

boleh mohon bantu ya auto reply guna DB untuk private chat dan group chat berbeda..

**Comment by ngekoding** [comment]
Konsepnya sama, jika ingin membedakan sumber data balasannya maka cukup buat tabel untuk masing-masing (private & group).

Berikut contohnya:

```
const keyword = msg.body.toLowerCase();
const chat = await msg.getChat();

if (chat.isGroup) {
  // Get reply message for group
  const replyMessage = await db.getGroupReply(keyword);
  msg.reply(replyMessage);
} else {
  // Get reply message for private
  const replyMessage = await db.getPrivateReply(keyword);
  msg.reply(replyMessage);
}
```

**Comment by mzayn** [comment]
> Konsepnya sama, jika ingin membedakan sumber data balasannya maka cukup buat tabel untuk masing-masing (private & group).
> 
> Berikut contohnya:
> 
> ```
> const keyword = msg.body.toLowerCase();
> const chat = await msg.getChat();
> 
> if (chat.isGroup) {
>   // Get reply message for group
>   const replyMessage = await db.getGroupReply(keyword);
>   msg.reply(replyMessage);
> } else {
>   // Get reply message for private
>   const replyMessage = await db.getPrivateReply(keyword);
>   msg.reply(replyMessage);
> }
> ```

gimana kalau code asalnya seperti contoh ini 


1.
```
 if (msg.body.toLowerCase() == 'good morning' && !chat.isGroup) {
    msg.reply('selamat pagi');

ini codenya sebagai tolowecase and for private chat. 
```


2.
```
if (msg.body.toLowerCase().startsWith(" ping") || msg.body.toLowerCase() == "ping"  && !chat.isGroup) {
    msg.reply('what pingpong ?');

ini codenya sebagai : kirim pesan sebagai pingpong > autobotnya gak bisa reply "what pingpong ?" - sebab digunakan code (" ping") di awalan. 
```


3.
```
const contact = await msg.getContact()
client.on('message', async msg => {
    
  if (msg.mentionedIds.includes(client.info.wid._serialized)) {// 
     const contact = await msg.getContact()
    client.sendMessage(msg.from, `Hello pak, kenapa mention ya @${contact.number} ? `, { mentions: [contact] });

ini codenya untuk mention nama WA pemanggil > jika WA kita di mention di dalam group > so auto bot akan reply di group. 
```

-------

So pak, gimana mau buat dalam bentuk Database untuk 3 code berbeda di atas pak. Mohon bantu...

terima kasih.

Stay safe
