### ISSUE TITLE
saat jalankan app-multiple-device barcode tidak muncul

### ISSUE THREAD

**Issue by viergiawan96** [ngekoding/whatsapp-api-tutorial#46]
saya coba jalankan app-multiple- device tidak muncul barcode di front end nya sedangkan saya cek di cmd QR reviceved id jalan,
kodingan tidak ada yang saya ubah dan saya coba menggunakan web whatsaap js terbaru juga tidak bisa,
mohon pencerahan nya

Terima kasih
![Capture](https://user-images.githubusercontent.com/47542917/114202946-e6fb6c80-9981-11eb-80bb-139f87dd7a6a.JPG)

**Comment by anderiansyah** [comment]
saya juga mengalami hal yang sama pak..
saya merubah link cdn pada inde-multiple-device.html menjadi seperti ini

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>

baarcode muncul

**Comment by ngekoding** [comment]
Coba IDnya gunakan huruf, jangan angka semua.

**Comment by viergiawan96** [comment]
kemarin sudah saya coba dan berhasil tapi saya masih ada yg bingung soal cek register wa di multiple device, untuk cara cek ny gmn ya mas ?terima kasih sebelum ny

**Comment by ngekoding** [comment]
Silahkan buat issue baru untuk pertanyaan yang berbeda.

**Comment by diazzaid** [comment]
> Coba IDnya gunakan huruf, jangan angka semua.

work gan
