### ISSUE TITLE
perwakilan kata

### ISSUE THREAD

**Issue by piak1110** [ngekoding/whatsapp-api-tutorial#5]
saya mau bertanya mas misalkan saya sudah buat seperti dibawah ini

client.on('message', msg => {
  if (msg.body == '!ping') {
    msg.reply('pong');
  } else if (msg.body == 'selamat pagi') {
    msg.reply('selamat pagi');
  } else if (msg.body == '!groups') {
    client.getChats().then(chats => {
      const groups = chats.filter(chat => chat.isGroup);

      if (groups.length == 0) {
        msg.reply('You have no group yet.');
      } else {
        let replyMsg = '*YOUR GROUPS*\n\n';
        groups.forEach((group, i) => {
          replyMsg += `ID: ${group.id._serialized}\nName: ${group.name}\n\n`;
        });
        replyMsg += '_You can use the group id to send a message to the group._'
        msg.reply(replyMsg);
      }
    });
  }
});

bagaimana cara nya ketika kita chat "selamat pagi kak" atau "selamat pagi buk" tetap di balas "Selamat Pagi" dan tidak terpengaruh dengan huruf besar ataupun huruf kecil

**Comment by ngekoding** [comment]
Pertama, hal itu terkait dengan JavaScript dasar, jadi mungkin bisa lebih diperhatikan untuk mempelajari hal-hal dasar dari JavaScript.

Adapun solusinya bisa menggunakan fungsi `includes`, ini fungsinya untuk mengecek string/sub-string pada sebuah string.

Sehingga fungsi di atas diubah menjadi:

```
if (msg.toLowerCase().includes('selamat pagi')) {
  msg.reply('Selamat Pagi');
}
```

Fungsi toLowerCase di atas untuk mengubahnya menjadi huruf kecil semua, sehingga tidak masalah jika dengan huruf kapital yang lainnya.

Semoga membantu.

**Comment by piak1110** [comment]
terima kasih banyak mas

**Comment by ngekoding** [comment]
Sama-sama.
