### ISSUE TITLE
auto reply unread message

### ISSUE THREAD

**Issue by sokaru** [ngekoding/whatsapp-api-tutorial#51]
sebelumnya terimakasih buat tutorialnya, saya sudah mencobanya dan ingin bertanya bagaimana caranya agar chat yang belum terbaca juga bisa di auto reply, 
maksudnya begini, ketika aplikasi offline (belum run) ada pesan masuk dan belum terbaca, lalu ketika aplikasi dijalankan maka pesan tersebut diharapkan dapat balasan juga. mohon pencerahannya.

**Comment by ngekoding** [comment]
Secara asal hal tersebut tidak bisa dilakukan, karena konsepnya adalah Bot hanya bisa menerima pesan ketika sedang berjalan. Akan tetapi, alternatif solusinya bisa menggunakan cara berikut.

Idenya adalah dengan mengambil pesan yang belum dibaca pada semua chat yang ada. Hal ini bisa memanfaatkan beberapa fungsi yang sudah disediakan oleh library whatsapp-web.js

1. Gunakan method `unreadCount` untuk mendapatkan jumlah pesan yang belum terbaca (ref: https://pedroslopez.me/whatsapp-web.js/Chat.html#unreadCount)
2. Gunakan method `fetchMessages` untuk mengambil pesan, manfaatkan unreadCount sebagai limit pesannnya, sehingga yang terambil hanya pesan yang belum terbaca saja (ref: https://pedroslopez.me/whatsapp-web.js/PrivateChat.html#fetchMessages)

Semoga dapat dipahami dan bisa membantu.

**Comment by sokaru** [comment]
Terimakasih, saya sudah mencobanya dan sudah berhasil.

**Comment by mzayn** [comment]
> Secara asal hal tersebut tidak bisa dilakukan, karena konsepnya adalah Bot hanya bisa menerima pesan ketika sedang berjalan. Akan tetapi, alternatif solusinya bisa menggunakan cara berikut.
> 
> Idenya adalah dengan mengambil pesan yang belum dibaca pada semua chat yang ada. Hal ini bisa memanfaatkan beberapa fungsi yang sudah disediakan oleh library whatsapp-web.js
> 
> 1. Gunakan method `unreadCount` untuk mendapatkan jumlah pesan yang belum terbaca (ref: https://pedroslopez.me/whatsapp-web.js/Chat.html#unreadCount)
> 2. Gunakan method `fetchMessages` untuk mengambil pesan, manfaatkan unreadCount sebagai limit pesannnya, sehingga yang terambil hanya pesan yang belum terbaca saja (ref: https://pedroslopez.me/whatsapp-web.js/PrivateChat.html#fetchMessages)
> 
> Semoga dapat dipahami dan bisa membantu.

bisa dibuat tutorialnya mas ?

**Comment by vedricopane** [comment]
> Terimakasih, saya sudah mencobanya dan sudah berhasil.

Apakah bisa share link githup nya mas ? Saya ada mengalamin kendala dalam penerapannya. Makasih
