### ISSUE TITLE
panel cmd ditutup, wa tidak bisa kirim pesan

### ISSUE THREAD

**Issue by iconix-id** [ngekoding/whatsapp-api-tutorial#52]
saya menggunakan vps, ubuntu 18, saat jalankan npm run start:dev (lewat panel termius), jalan baik, tapi saat panel termius ditutup, wa gak bisa lakukan apa2 lagi.
saat buka dan jalankan lagi npm run start:dev, ada warning port 8000 masih terpakai, sehingga harus restart vps agar WA bisa jalan.
bagaimana cara mengatasi hal ini ?

mohon sarannya mas, terimakasih.

**Comment by ngekoding** [comment]
Pada video tutorial sudah dijelaskan, untuk keperluan production silahkan gunakan pm2 (ref: https://pm2.keymetrics.io/docs/usage/quick-start)
