### ISSUE TITLE
inviteCode

### ISSUE THREAD

**Issue by riagie** [ngekoding/whatsapp-api-tutorial#53]
ada code untuk getInviteInfo atau acceptInvite ?

**Comment by ngekoding** [comment]
Silahkan bisa mereferensi dari beberapa link berikut:

- https://pedroslopez.me/whatsapp-web.js/GroupChat.html#getInviteCode
- https://pedroslopez.me/whatsapp-web.js/Client.html#acceptInvite
- https://github.com/pedroslopez/whatsapp-web.js/blob/master/example.js (cari dengan keyword 'invite')
