### ISSUE TITLE
(node:22044) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by ninegrafh** [ngekoding/whatsapp-api-tutorial#54]
saya coba jalankan untuk kirim file gambar eror

![eror1](https://user-images.githubusercontent.com/41564272/117261924-ebc91880-ae7a-11eb-8828-3650288cf17e.png)
![Untitled](https://user-images.githubusercontent.com/41564272/117262710-bffa6280-ae7b-11eb-8013-684984834dc1.jpg)

**Comment by ngekoding** [comment]
Silahkan sertakan kodenya.

**Comment by ninegrafh** [comment]
code saya ambil dari respisitory ngekoding whatsapp-api-tutorial masih ori (belum saya edit)

Run npm install
Run npm run start:dev

waktu saya scan qr 
![1](https://user-images.githubusercontent.com/41564272/117415516-9a845c00-af42-11eb-8a53-022bdc5338d9.png)
![2](https://user-images.githubusercontent.com/41564272/117415520-9bb58900-af42-11eb-9118-e162d48a4a8a.png)

**Comment by ngekoding** [comment]
SIlahkan ikuti tutorial [Whatsapp API Tutorial: Sending Media File](https://youtu.be/ksVBXF-6Jtc) agar lebih jelas, ada beberapa macam cara yang sudah dicontohkan, dan kode di repository ini perlu disesuaikan sesuai sumber media yang akan dikirim.

**Comment by ravi2143** [comment]
> i have the same issue i found the file is undefined due to that this error is coming. but how to resolve this.
> 
> const fileUrl = req.body.file;
> 
> fileUrl is undefined

my mistake it working grate thank you
