### ISSUE TITLE
Sudah Deploy ke Heroku dan berjalan lancar cuma kadang tidak pasti beberapa hari sessionya ilang perlu login lagi 

### ISSUE THREAD

**Issue by natsirasrafi** [ngekoding/whatsapp-api-tutorial#55]
Sudah Deploy ke Heroku dan berjalan lancar cuma kadang tidak pasti beberapa hari sessionya ilang perlu login lagi , sudah pakai penyimpanan ke database postgre,  ada solusi atau semestinya bagaimana agar memastikan selalu live ?

**Comment by ngekoding** [comment]
Apakah nomornya dipakai untuk whatsapp web di tempat lain?
