### ISSUE TITLE
Gambar QR tidak muncul ketika ID memakai nomer hp

### ISSUE THREAD

**Issue by sangajiputra** [ngekoding/whatsapp-api-tutorial#56]
Waktu menggunakan multiple device saya masukkan ID nya bukan dengan primary atau secondary tapi dengan nomer hp.

Tapi kenapa waktu di browser buat munculin qr nya malah gabisa? tapi di console keluar untuk base64 nya

**Comment by ngekoding** [comment]
Terima kasih atas laporannya. 

Adapun mengenai hal tersebut memang keterbatasan dari selector yang tidak bisa menggunakan awalan angka. Saya terluput bagian ini sehingga tidak menjelaskannya di video.

Kemudian bagaimana solusinya?

Silahkan bisa tambahkan karakter tertentu sebagai awalan di kode tambah client-nya, cukup di kodenya saja, adapun yang ditampilkan tetap nomornya saja. 

Misal diubah menjadi seperti berikut:

```
var template = $('.client')
.first()
.clone()
.removeClass('hide')
.addClass('client-' + clientId); // Bagian ini yang disesuaikan
```
*Silahkan disesuaikan bagian yang lainnya juga.

Semoga membantu.
