### ISSUE TITLE
tutor forward messages

### ISSUE THREAD

**Issue by lurahxp** [ngekoding/whatsapp-api-tutorial#57]
jika luang, saya sangat senang jika dibuatkan tutorial forward.
saya sudah berhasil forward, hanya saja ketika terima pesan, kemudian langsung di forward, itu bisa
di client.on('message', message => {
tapi jika forward pesan lama, saya belum tahu caranya
coba beralih ke venom-bot, masih belum sukses

terima kasih banyak

**Comment by ngekoding** [comment]
Silahkan bisa merujuk ke issue ini https://github.com/ngekoding/whatsapp-api-tutorial/issues/51, konsepnya sama dengan kebutuhan ini.
