### ISSUE TITLE
message nya ga muncul

### ISSUE THREAD

**Issue by ade566** [ngekoding/whatsapp-api-tutorial#58]
Habis scan qr code (belum di reload)
![image](https://user-images.githubusercontent.com/49903115/119926481-b5764900-bfa1-11eb-8229-d25cb8622b87.png)

sesudah di reload
![image](https://user-images.githubusercontent.com/49903115/119926629-ece4f580-bfa1-11eb-8aa0-9a9d635b4d51.png)

kenapa message nya ga sama ya mas?

**Comment by ngekoding** [comment]
Silahkan ikuti tutorial selanjutnya sampai selesai, ada penjelasan dan penyesuiannya.

**Comment by windugi** [comment]
@ngekoding kalau boleh tau tutorial yang mana ya? masih belum tercerahkan
