### ISSUE TITLE
request : auto reply on app-multiple-device.js

### ISSUE THREAD

**Issue by diazzaid** [ngekoding/whatsapp-api-tutorial#59]
mohon di tambahkan fitur auto reply seperti yang ada ada single device.
terima kasih
kode

client.on('message', msg =&gt; {  
if (msg.body == '!ping') {    msg.reply('pong');  } 
else if (msg.body == 'good morning') {    msg.reply('selamat pagi');  } 
else if (msg.body == '!groups') {    client.getChats().then(chats =&gt; {      
const groups = chats.filter(chat =&gt; chat.isGroup);
      if (groups.length == 0) {        msg.reply('You have no group yet.');      } 
else {        let replyMsg = '*YOUR GROUPS*\n\n';        groups.forEach((group, i) =&gt; {          replyMsg += `ID: ${group.id._serialized}\nName: ${group.name}\n\n`;        });        
replyMsg += '_You can use the group id to send a message to the group._'        msg.reply(replyMsg);      }    });  }});<!--

**Comment by ngekoding** [comment]
Silahkan diperbaiki penulisan kodenya agar lebih rapi dan mudah dibaca.

**Comment by diazzaid** [comment]
sudah mas.

**Comment by diazzaid** [comment]
> Silahkan diperbaiki penulisan kodenya agar lebih rapi dan mudah dibaca.

sudah mas

**Comment by ngekoding** [comment]
Di dalam fungsi createSession tambahkan kodenya.

```
const createSession = function(id, description) {
  ...
  client.initialize();
  ...
  client.on('message', msg => {
    if (msg.body == '!ping') {
      msg.reply('pong');
    } else if (msg.body == 'good morning') {
      msg.reply('selamat pagi');
    }
  });
}
```

**Comment by diazzaid** [comment]
> Di dalam fungsi createSession tambahkan kodenya.
> 
> ```
> const createSession = function(id, description) {
>   ...
>   client.initialize();
>   ...
>   client.on('message', msg => {
>     if (msg.body == '!ping') {
>       msg.reply('pong');
>     } else if (msg.body == 'good morning') {
>       msg.reply('selamat pagi');
>     }
>   });
> }
> ```

ok mas nuhun sudah bisa
cuma ada yg harus d delet bagian akhir } 
jadi 
client.on('message', msg => {
    if (msg.body == '!ping') {
      msg.reply('pong');
    } else if (msg.body == 'good morning') {
      msg.reply('selamat pagi');
    }
  });
