### ISSUE TITLE
TypeError: Cannot read property 'client' of undefined at C:\xampp\htdocs\api-wa\app-multiple.js:185:58

### ISSUE THREAD

**Issue by ade566** [ngekoding/whatsapp-api-tutorial#62]
ini kenapa bisa gitu ya mas,
[https://github.com/ade566/app-multiple-device.wa.nodejs/blob/main/app-multiple.js](https://github.com/ade566/app-multiple-device.wa.nodejs/blob/main/app-multiple.js)
![image](https://user-images.githubusercontent.com/49903115/121113170-c6de1180-c83b-11eb-8f00-6dc9448674ec.png)
![image](https://user-images.githubusercontent.com/49903115/121113221-deb59580-c83b-11eb-8aca-bbf8adfa81f5.png)

**Comment by ngekoding** [comment]
Pastikan parameter sender sudah diberikan sesuai client yang dibuat sebelumnya, penjelasannya ada pada video tutorial, silahkan disimak melalui link berikut https://youtu.be/5VfM9PvrYcE?t=2223

**Comment by ade566** [comment]
oh saya ngerti mas kenapa bisa error seperti di atas, tapi apa itu mempengaruhi perfomanya mas? soalnya saya buat fitur kalo sender-id ga bisa ngirim ganti sender-id yang lain secara looping sampai terkirim / looping sender-id habis

**Comment by ngekoding** [comment]
Tidak masalah.

**Comment by ade566** [comment]
ok, terimakasih mas
