### ISSUE TITLE
integrasi plugin woocomerce

### ISSUE THREAD

**Issue by diazzaid** [ngekoding/whatsapp-api-tutorial#64]
mas mau tanya apa bisa di integrasikan dengan wp woocommerce ?

**Comment by ngekoding** [comment]
Seharusnya bisa, tapi saya belum ada rencana ke arah sana.

**Comment by diazzaid** [comment]
sudah berhasil mas.
install plugin wpnotif dan pilih custom sms arahkan sesuai api yang digunakan
![image](https://user-images.githubusercontent.com/25816482/124347206-8d67ae80-dc0d-11eb-91bb-da2161ffe4d3.png)
