### ISSUE TITLE
Gagal kirim pesan heroku

### ISSUE THREAD

**Issue by ade566** [ngekoding/whatsapp-api-tutorial#69]
Jadi api yg saya buat ini lancar ketika di coba untuk melakukan blast WhatsApp (localhost), tapi ketika di coba di heroku selalu gagal walau sudah log 'Ready'. kenapa ya mas bisa seperti itu?

**Comment by ngekoding** [comment]
Silahkan cek log di Heroku dan sertakan respon APInya untuk mempermudah debugging.
