### ISSUE TITLE
QRCODE does not appear

### ISSUE THREAD

**Issue by cruizer468** [ngekoding/whatsapp-api-tutorial#7]
i have tried in my windows terminal and to launch in heroku but the qrcode does not apper , what is the problem ?
![tutorial](https://user-images.githubusercontent.com/36890086/99807858-a6d25380-2b72-11eb-9b53-eb85ddd9c9f4.JPG)

**Comment by R3N4L** [comment]
Sama pak..

**Comment by muazinasro** [comment]
iya sama

**Comment by ngekoding** [comment]
Beberapa hal yang perlu diperhatikan:
1. Gunakan library `whatsapp-web.js` versi terakhir
2. Tambahkan buildpack untuk Puppeteer

Poin kedua telah dijelaskan pada video tutorial.

- 
Make sure you have doing this right
1. Use the latest version of `whatsapp-web.js`
2. Add buildpack for Pupputeer

The second point was mentioned in the video tutorial.
