### ISSUE TITLE
error pada saat upload gambar

### ISSUE THREAD

**Issue by mpampamdev** [ngekoding/whatsapp-api-tutorial#70]
![dsad](https://user-images.githubusercontent.com/74229073/124506433-d67a5700-ddf5-11eb-99b0-f052b43b68bf.PNG)

**Comment by ngekoding** [comment]
Jika langsung menggunakan kode pada repositori ini memang akan menjadi kendala saat mengirim pesan media, penjelasan penggunaannya bisa dilihat pada tutorial terlebih dulu. Silahkan simak [Whatsapp API Tutorial: Sending Media File
](https://youtu.be/ksVBXF-6Jtc)

**Comment by mpampamdev** [comment]
makasih mass

Pada tanggal Sel, 6 Jul 2021 pukul 07.57 Nur Muhammad <
***@***.***> menulis:
