### ISSUE TITLE
error this.#convertToExtended(); di Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by yan043** [ngekoding/whatsapp-api-tutorial#74]
padahal nodejs sudah di update, mohon bantuannya abang-abang

![Screenshot_2](https://user-images.githubusercontent.com/62176525/125445149-09fa6115-b5ac-4f9b-812d-61a66e65f0ae.png)

**Comment by ngekoding** [comment]
Silahkan gunakan Node.js v14

**Comment by ngekoding** [comment]
Serta gunakan versi terbaru dari whatsapp-web.js

**Comment by diazzaid** [comment]
> padahal nodejs sudah di update, mohon bantuannya abang-abang
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/62176525/125445149-09fa6115-b5ac-4f9b-812d-61a66e65f0ae.png)

coba cara ini #71

**Comment by yan043** [comment]
solved, makasih bang
