### ISSUE TITLE
request : rotate sender

### ISSUE THREAD

**Issue by diazzaid** [ngekoding/whatsapp-api-tutorial#78]
mas gimana caranya ya supaya yang multi device bisa auto rotate sender

**Comment by ngekoding** [comment]
Maaf saya belum paham maksudnya 'rotate sender' seperti apa?

**Comment by diazzaid** [comment]
> Maaf saya belum paham maksudnya 'rotate sender' seperti apa?

jadi gini mas. kn yang multi device itu akses api nya pke body "sender" 
nah misal kan sy punya lebih dari satu sender, tetapi ingin di load balancing sender nya, misal sender nya jd "balancer" di arahkan roun robin ke 2 akun whatsapp yang sudah konek sebelum nya misal sender1 dan sender2,

**Comment by ngekoding** [comment]
Oh tidak masalah mas, karena sendernya sudah disimpan di variabel `sessions` sehingga mudah untuk mengelola penggunaan client-nya. Disesuaikan dengan kebutuhan saja.
