### ISSUE TITLE
Always Connecting... 

### ISSUE THREAD

**Issue by MuhShalah007** [ngekoding/whatsapp-api-tutorial#8]
![image](https://user-images.githubusercontent.com/44994363/100167808-7d0e8900-2ef2-11eb-9a48-84944fa2a8a9.png)

Selalu dapat status "Connecting..." saat di reload di socket pada file index.html setelah dapat status "Whatsapp is ready!"

**Comment by ngekoding** [comment]
Ketika reload browser maka koneksi socket akan diulang, dan connecting... itu hanya sebagai penanda bahwa koneksi socket berhasil. Silahkan bisa menambahkan logik untuk mengirimkan status client saat ini ketika ada koneksi socket.

Misalnya dapat ditambahkan sebuah variable baru `isReady`, sehingga ketika client ready/failure nilainya diubah. Kemudian ketika ada koneksi socket, selain mengirim connecting... juga mengirim status `isReady` itu.

Semoga dapat dipahami.

**Comment by MuhShalah007** [comment]
Maaf saya masih kurang paham tentang per socket-an ada kah contoh yang bisa digunakan?

**Comment by ngekoding** [comment]
Hal yang saja sebutkan di atas tidak berkaitan langsung dengan socket, tapi lebih ke alur program.

Konsepnya adalah, kita membuat sebuah variabel yang menyimpan nilai ready (isReady).Dan ketika sudah berhasil discan (ready), maka ubah bilai isReady menjadi TRUE.

Sehingga ketika browser direload, kirimkan status isReady itu (sama dengan cara mengirim connecting...) itu. Jika nilai isReady TRUE, maka tampilkan sudah ready.

Semoga dapat dipahami.
—

Jangan lupa menjadikan nilai isReady menjadi FALSE jika client tidak ready, dimana menentukannya? Bisa saat event disconnected atau auth failure.
