### ISSUE TITLE
Timeout dari puppeteer

### ISSUE THREAD

**Issue by sangajiputra** [ngekoding/whatsapp-api-tutorial#80]
Ketika saya masukan ke vps selalu muncul seperti ini

(node:437029) UnhandledPromiseRejectionWarning: TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r818858 is guaranteed to work.

mohon bantuannya itu kenapa?
saya baca itu karena timeoutnya belum di ganti
kalo di puppeteer nya katanya bisa pakai { waitUntil: 'load', timeout: 0 } di goto option nya

tapi kalau disini bagaimana?

**Comment by ngekoding** [comment]
Sudah coba gunakan versi terbaru dari whatsapp-web.js?
Dan jangan lupa veris Node.js harus v14 atau yang lebih baru

**Comment by sangajiputra** [comment]
sudah pak

> Sudah coba gunakan versi terbaru dari whatsapp-web.js?
> Dan jangan lupa veris Node.js harus v14 atau yang lebih baru

**Comment by ngekoding** [comment]
Jika ingin mengubah pengaturan di puppeteer-nya, bisa dengan cara berikut ini:

```js
const client = new Client({
    puppeteer: {
        timeout: 30000 // default is 30s
    }
})
```
Silahkan bisa disesuaikan untuk pengaturan yang lainnya sesuai kebutuhan.
