### ISSUE TITLE
Error saat Package Node JS Project

### ISSUE THREAD

**Issue by novrialsyah** [ngekoding/whatsapp-api-tutorial#82]
D:\whatsapp\NurMuhammad\bag1>pkg app.js --targets node14-win-x64
> pkg@5.3.0
> Warning Cannot resolve 'SESSION_FILE_PATH'
  D:\whatsapp\NurMuhammad\bag1\app.js
  Dynamic require may fail at run time, because the requested file
  is unknown at compilation time and not included into executable.
  Use a string literal as an argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Error! This experimental syntax requires enabling the parser plugin: 'classPrivateMethods' (441:2)

file app.js
const { Client } = require('whatsapp-web.js');
const qrcode = require('qrcode-terminal');
const fs = require('fs');

const SESSION_FILE_PATH = './whatsapp-session.json';
let sessionCfg;
if (fs.existsSync(SESSION_FILE_PATH)) {
    sessionCfg = require(SESSION_FILE_PATH);
}

const client = new Client({ puppeteer: { headless: true }, session: sessionCfg });

client.on('qr', (qr) => {
    console.log('QR RECEIVED', qr);
	qrcode.generate(qr);
});

client.on('authenticated', (session) => {
    console.log('AUTHENTICATED', session);
    sessionCfg=session;
    fs.writeFile(SESSION_FILE_PATH, JSON.stringify(session), function (err) {
        if (err) {
            console.error(err);
        }
    });
});

client.on('ready', () => {
    console.log('Client is ready!');
});

client.on('message', msg => {
    if (msg.body == '!ping') {
        msg.reply('pong');
    }
});

client.initialize();

**Comment by ngekoding** [comment]
Saya agak asing dengan perintah yang digunakan, apakah menggunakan windows?

**Comment by novrialsyah** [comment]
benar menggunakan windows..

**Comment by novrialsyah** [comment]
jika menggunakan linux perintah apa yang dapat saya coba?

**Comment by ngekoding** [comment]
Kebetulan saya tidak ada windows untuk mencoba, tapi saya menyarankan untuk melakukan instalasi Node.js terlebih dulu.

1. Unduh dan install Node.js https://nodejs.org/en/download/
2. Jalankan dengan perintah `node app.js`

**Comment by ngekoding** [comment]
> jika menggunakan linux perintah apa yang dapat saya coba?

Sebenarnya caranya sama saja, yang penting sudah install Node.js
