### ISSUE TITLE
response in server Node, post callback in java

### ISSUE THREAD

**Issue by gmlmaino** [ngekoding/whatsapp-api-tutorial#84]
Hello, how are you, I wanted to thank you for the video from the WhatsApp server, it served me and I was trying to use it in a java application that makes notifications via WhatsApp,
I am trying to make a response to a java web app that sends a notification Like sms or wp message, it doesn't matter that, the app sends an async message, this post is written in java, and what I have to do in node express, return the response for this app, make a callback and finish sending the post.

I can't understand what the callback does, what it is waiting for it to respond to successfully follow the function, because in the app in the error log it gives me WARN: SmS API error - Error at index 0 in: « null »- NumberFormatException (…)
package org.acceso.notificators;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.slf4j.LoggerFactory;
import org.acceso.model.User;
import javax.ws.rs.client.InvocationCallback;
import javax.ws.rs.client.Entity;
import org.acceso.notification.NotificationFormatter;
import org.acceso.model.Position;
import org.acceso.model.Event;
import org.acceso.Context;
import org.slf4j.Logger;

public class NotificatorSms extends Notificator
{
    private static final Logger LOGGER;
    private String url;
    private String token;

    public NotificatorSms() {
        this.url = ((Context.getConfig().getString(«notificator.sms.url») != null) ? (Context.getConfig().getString(«notificator.sms.url») + «/api/send/») : String.format(«http://sms.gpstracking.ar:%s/api/send/», Context.getConfig().getString(«notificator.sms.port»)));
        this.token = Context.getConfig().getString(«notificator.sms.token»);
    }

    @Override
    public void sendSync(final long userId, final Event event, final Position position) {
        final User user = Context.getPermissionsManager().getUser(userId);
        final Object sms= user.getSms();
        final String SmsNumber = (sms== null) ? «» : sms.toString();
        if (SmsNumber.length() > 0) {
            final Message message = new Message();
            message.phone = SmsNumber.toString();
            message.message = NotificationFormatter.formatSmsMessage(userId, event, position);
            **Context.getClient().target(this.url + this.token).request().async().post(Entity.json((Object)message), (InvocationCallback)new InvocationCallback<Object>() {**
                public void completed(final Object o) {
                }

                public void failed(final Throwable throwable) {
                    NotificatorSms.LOGGER.warn(«Sms API error», throwable);
                }
            });
        }
        else {
            NotificatorSms.LOGGER.warn(«Sms parameter error:», (Object)(«User » + user.getName() + » does not have Sms phone»));
        }
    }

    @Override
    public void sendAsync(final long userId, final Event event, final Position position) {
        this.sendSync(userId, event, position);
    }

    static {
        LOGGER = LoggerFactory.getLogger((Class)NotificatorSms.class);
    }

    public static class Message
    {
        @JsonProperty(«phone»)
        private String phone;
        @JsonProperty(«message»)
        private String message;
    }
}

Thanks, what I wanted is to make the part of the server that attends the post from java and attends the callbacks, the issue is that I do not understand how the callbacks work to answer in node

**Comment by ngekoding** [comment]
I am not sure your code pasted correctly, please recheck!

**Comment by ngekoding** [comment]
And please, edit the title with English, I really don't understand.

**Comment by gmlmaino** [comment]
//Code java

package org.acceso.notificators;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.slf4j.LoggerFactory;
import org.acceso.model.User;
import javax.ws.rs.client.InvocationCallback;
import javax.ws.rs.client.Entity;
import org.acceso.notification.NotificationFormatter;
import org.acceso.model.Position;
import org.acceso.model.Event;
import org.acceso.Context;
import org.slf4j.Logger;

public class NotificatorSms extends Notificator
{
private static final Logger LOGGER;
private String url;
private String token;

public NotificatorSms() {
    this.url = ((Context.getConfig().getString(«notificator.sms.url») != null) ? (Context.getConfig().getString(«notificator.sms.url») + «/api/send/») : String.format(«http://sms.gpstracking.ar:%s/api/send/», Context.getConfig().getString(«notificator.sms.port»)));
    this.token = Context.getConfig().getString(«notificator.sms.token»);
}

@Override
public void sendSync(final long userId, final Event event, final Position position) {
    final User user = Context.getPermissionsManager().getUser(userId);
    final Object sms= user.getSms();
    final String SmsNumber = (sms== null) ? «» : sms.toString();
    if (SmsNumber.length() > 0) {
        final Message message = new Message();
        message.phone = SmsNumber.toString();
        message.message = NotificationFormatter.formatSmsMessage(userId, event, position);
        Context.getClient().target(this.url + this.token).request().async().post(Entity.json((Object)message), (InvocationCallback)new InvocationCallback<Object>() {
            public void completed(final Object o) {
            }

            public void failed(final Throwable throwable) {
                NotificatorSms.LOGGER.warn(«Sms API error», throwable);
            }
        });
    }
    else {
        NotificatorSms.LOGGER.warn(«Sms parameter error:», (Object)(«User » + user.getName() + » does not have Sms phone»));
    }
}

@Override
public void sendAsync(final long userId, final Event event, final Position position) {
    this.sendSync(userId, event, position);
}

static {
    LOGGER = LoggerFactory.getLogger((Class)NotificatorSms.class);
}

public static class Message
{
    @JsonProperty(«phone»)
    private String phone;
    @JsonProperty(«message»)
    private String message;
}
}

**Comment by gmlmaino** [comment]
package org.sms.notificators;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.slf4j.LoggerFactory;
import org.sms.model.User;
import javax.ws.rs.client.InvocationCallback;
import javax.ws.rs.client.Entity;
import org.sms.notification.NotificationFormatter;
import org.sms.model.Position;
import org.sms.model.Event;
import org.sms.Context;
import org.slf4j.Logger;

public class NotificatorWhatsapp extends Notificator
{
    private static final Logger LOGGER;
    private String url;
    private String token;
    
    public NotificatorWhatsapp() {
        this.url = ((Context.getConfig().getString("notificator.whatsapp.url") != null) ? (Context.getConfig().getString("notificator.whatsapp.url") + "/api/send/") : String.format("http://whatsapp.centralderastreamentogps.com.br:%s/api/send/", Context.getConfig().getString("notificator.whatsapp.port")));
        this.token = Context.getConfig().getString("notificator.whatsapp.token");
    }
    
    @Override
    public void sendSync(final long userId, final Event event, final Position position) {
        final User user = Context.getPermissionsManager().getUser(userId);
        final Object wpp = user.getWhatsapp();
        final String whatsappNumber = (wpp == null) ? "" : wpp.toString();
        if (whatsappNumber.length() > 0) {
            final Message message = new Message();
            message.phone = whatsappNumber.toString();
            message.message = NotificationFormatter.formatWhatsappMessage(userId, event, position);
            Context.getClient().target(this.url + this.token).request().async().post(Entity.json((Object)message), (InvocationCallback)new InvocationCallback<Object>() {
                public void completed(final Object o) {
                }
                
                public void failed(final Throwable throwable) {
                    NotificatorWhatsapp.LOGGER.warn("Whatsapp API error", throwable);
                }
            });
        }
        else {
            NotificatorWhatsapp.LOGGER.warn("Whatsapp parameter error:", (Object)("User " + user.getName() + " does not have whatsapp phone"));
        }
    }
    
    @Override
    public void sendAsync(final long userId, final Event event, final Position position) {
        this.sendSync(userId, event, position);
    }
    
    static {
        LOGGER = LoggerFactory.getLogger((Class)NotificatorWhatsapp.class);
    }
    
    public static class Message
    {
        @JsonProperty("phone")
        private String phone;
        @JsonProperty("message")
        private String message;
    }
}

**Comment by gmlmaino** [comment]
package org.traccar.notificators;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.slf4j.LoggerFactory;
import org.traccar.model.User;
import javax.ws.rs.client.InvocationCallback;
import javax.ws.rs.client.Entity;
import org.traccar.notification.NotificationFormatter;
import org.traccar.model.Position;
import org.traccar.model.Event;
import org.traccar.Context;
import org.slf4j.Logger;

public class NotificatorWhatsapp extends Notificator
{
    private static final Logger LOGGER;
    private String url;
    private String token;
    
    public NotificatorWhatsapp() {
        this.url = ((Context.getConfig().getString("notificator.whatsapp.url") != null) ? (Context.getConfig().getString("notificator.whatsapp.url") + "/api/send/") : String.format("http://whatsapp.centralderastreamentogps.com.br:%s/api/send/", Context.getConfig().getString("notificator.whatsapp.port")));
        this.token = Context.getConfig().getString("notificator.whatsapp.token");
    }
    
    @Override
    public void sendSync(final long userId, final Event event, final Position position) {
        final User user = Context.getPermissionsManager().getUser(userId);
        final Object wpp = user.getWhatsapp();
        final String whatsappNumber = (wpp == null) ? "" : wpp.toString();
        if (whatsappNumber.length() > 0) {
            final Message message = new Message();
            message.phone = whatsappNumber.toString();
            message.message = NotificationFormatter.formatWhatsappMessage(userId, event, position);
            Context.getClient().target(this.url + this.token).request().async().post(Entity.json((Object)message), (InvocationCallback)new InvocationCallback<Object>() {
                public void completed(final Object o) {
                }
                
                public void failed(final Throwable throwable) {
                    NotificatorWhatsapp.LOGGER.warn("Whatsapp API error", throwable);
                }
            });
        }
        else {
            NotificatorWhatsapp.LOGGER.warn("Whatsapp parameter error:", (Object)("User " + user.getName() + " does not have whatsapp phone"));
        }
    }
    
    @Override
    public void sendAsync(final long userId, final Event event, final Position position) {
        this.sendSync(userId, event, position);
    }
    
    static {
        LOGGER = LoggerFactory.getLogger((Class)NotificatorWhatsapp.class);
    }
    
    public static class Message
    {
        @JsonProperty("phone")
        private String phone;
        @JsonProperty("message")
        private String message;
    }
}

**Comment by gmlmaino** [comment]
`package org.traccar.notificators;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.slf4j.LoggerFactory;
import org.traccar.model.User;
import javax.ws.rs.client.InvocationCallback;
import javax.ws.rs.client.Entity;
import org.traccar.notification.NotificationFormatter;
import org.traccar.model.Position;
import org.traccar.model.Event;
import org.traccar.Context;
import org.slf4j.Logger;

public class NotificatorWhatsapp extends Notificator
{
    private static final Logger LOGGER;
    private String url;
    private String token;
    
    public NotificatorWhatsapp() {
        this.url = ((Context.getConfig().getString("notificator.whatsapp.url") != null) ? (Context.getConfig().getString("notificator.whatsapp.url") + "/api/send/") : String.format("http://whatsapp.centralderastreamentogps.com.br:%s/api/send/", Context.getConfig().getString("notificator.whatsapp.port")));
        this.token = Context.getConfig().getString("notificator.whatsapp.token");
    }
    
    @Override
    public void sendSync(final long userId, final Event event, final Position position) {
        final User user = Context.getPermissionsManager().getUser(userId);
        final Object wpp = user.getWhatsapp();
        final String whatsappNumber = (wpp == null) ? "" : wpp.toString();
        if (whatsappNumber.length() > 0) {
            final Message message = new Message();
            message.phone = whatsappNumber.toString();
            message.message = NotificationFormatter.formatWhatsappMessage(userId, event, position);
            Context.getClient().target(this.url + this.token).request().async().post(Entity.json((Object)message), (InvocationCallback)new InvocationCallback<Object>() {
                public void completed(final Object o) {
                }
                
                public void failed(final Throwable throwable) {
                    NotificatorWhatsapp.LOGGER.warn("Whatsapp API error", throwable);
                }
            });
        }
        else {
            NotificatorWhatsapp.LOGGER.warn("Whatsapp parameter error:", (Object)("User " + user.getName() + " does not have whatsapp phone"));
        }
    }
    
    @Override
    public void sendAsync(final long userId, final Event event, final Position position) {
        this.sendSync(userId, event, position);
    }
    
    static {
        LOGGER = LoggerFactory.getLogger((Class)NotificatorWhatsapp.class);
    }
    
    public static class Message
    {
        @JsonProperty("phone")
        private String phone;
        @JsonProperty("message")
        private String message;
    }
}

**Comment by gmlmaino** [comment]
package org.traccar.notificators;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.slf4j.LoggerFactory;
import org.traccar.model.User;
import javax.ws.rs.client.InvocationCallback;
import javax.ws.rs.client.Entity;
import org.traccar.notification.NotificationFormatter;
import org.traccar.model.Position;
import org.traccar.model.Event;
import org.traccar.Context;
import org.slf4j.Logger;

public class NotificatorWhatsapp extends Notificator
{
    private static final Logger LOGGER;
    private String url;
    private String token;
    
    public NotificatorWhatsapp() {
        this.url = ((Context.getConfig().getString("notificator.whatsapp.url") != null) ? (Context.getConfig().getString("notificator.whatsapp.url") + "/api/send/") : String.format("http://whatsapp.centralderastreamentogps.com.br:%s/api/send/", Context.getConfig().getString("notificator.whatsapp.port")));
        this.token = Context.getConfig().getString("notificator.whatsapp.token");
    }
    
    @Override
    public void sendSync(final long userId, final Event event, final Position position) {
        final User user = Context.getPermissionsManager().getUser(userId);
        final Object wpp = user.getWhatsapp();
        final String whatsappNumber = (wpp == null) ? "" : wpp.toString();
        if (whatsappNumber.length() > 0) {
            final Message message = new Message();
            message.phone = whatsappNumber.toString();
            message.message = NotificationFormatter.formatWhatsappMessage(userId, event, position);
            Context.getClient().target(this.url + this.token).request().async().post(Entity.json((Object)message), (InvocationCallback)new InvocationCallback<Object>() {
                public void completed(final Object o) {
                }
                
                public void failed(final Throwable throwable) {
                    NotificatorWhatsapp.LOGGER.warn("Whatsapp API error", throwable);
                }
            });
        }
        else {
            NotificatorWhatsapp.LOGGER.warn("Whatsapp parameter error:", (Object)("User " + user.getName() + " does not have whatsapp phone"));
        }
    }
    
    @Override
    public void sendAsync(final long userId, final Event event, final Position position) {
        this.sendSync(userId, event, position);
    }
    
    static {
        LOGGER = LoggerFactory.getLogger((Class)NotificatorWhatsapp.class);
    }
    
    public static class Message
    {
        @JsonProperty("phone")
        private String phone;
        @JsonProperty("message")
        private String message;
    }
[NotificatorSMS1.java.zip](https://github.com/ngekoding/whatsapp-api-tutorial/files/6890005/NotificatorSMS1.java.zip)

}

**Comment by gmlmaino** [comment]
in the .zip there is the code of the java app, which I cannot modify

**Comment by gmlmaino** [comment]
function inicial (message, Object, next)  {
  console.log(message.connection.remoteAddress);
  app.use(express.json()) // for parsing application/json
app.use(express.urlencoded({ extended: true })) // for parsing application/x-www-form-urlencoded
 
  const phone = phoneNumberFormatter(message.body.phone);
  const message1 = message.body.message;
  console.log('req'+ (message.body.phone));
  const isRegisteredNumber = checkRegisteredNumber(phone);
  
  next(); 
  if (!isRegisteredNumber) {
    return Object.status(200).json({
      status: false,
      message: 'The number is not registered'
    });
  }
  
  Object.status(200).json({
  phone: message.body.phone,
  message: message.body.message
  });
  console.log('inicial ' + Object);
  console.log('phone ' + message.body.phone);
  console.log('message ' + message.body.message);
  Object.end();

 
};

function final (Object, response, next) {

    const phone = phoneNumberFormatter(Object.body.phone);
    const message = Object.body.message;
  console.log('invocation ' + (Object.body.phone));
  

    client.sendMessage(phone, message).then(response => {
      response.status(200).json({
        status: true,
        response: response
      });
    }).catch(err => {
      response.json({
        status: false,
       response: err
      });
     
    });
    console.log('reponse final  ' + (response));
  };
  
app.post('/api/send/8s8d9s9fs9', inicial, final);
app.get('/api/send/8s8d9s9fs9', inicial, final);

**Comment by gmlmaino** [comment]
This is the code with which I want to respond to the post of the java app, I told you that I am not a 100% programmer, so they are my first steps in js and mode, but in java, almost nothing, and what I am trying to do is make the notification work, and it is failing me on line 34 of the zip
Context.getClient (). Target (this.url + this.token) .request (). Async (). Post (Entity.json ((Object) message), (InvocationCallback) new InvocationCallback <Object> ()
I do not know how that callback works, and if there are times that I am missing. I would like to know if you can advise me how to do it, thank you

**Comment by gmlmaino** [comment]
Node functions, tested with postman, work, I would have to tidy them up, but they don't work in the app, it is that it directly closes with log error because it does not get an adequate response or in adequate time from the node server
