### ISSUE TITLE
How to get image from the sender and then setting location directory?

### ISSUE THREAD

**Issue by z4cky87** [ngekoding/whatsapp-api-tutorial#89]
Mas mau nnya saya ngikutin yang tutorial whatsapp api.. gimana caranya menyimpan / download gambar dari pengirim , dan bagaimana cara menentukan directorynya misalnya ke sebuah folder yang sudah kita buat

**Comment by ngekoding** [comment]
Sebenarnya di dokumentasi sudah ada penjelasan singkatnya, bisa dibaca melalui link ini: https://guide.wwebjs.dev/features/handling-attachments

Apakah ada yang belum dipahami dari dokumentasi itu?

**Comment by z4cky87** [comment]
belum buka dokumentasi mas.. oke mas.. saya baca dlu.. smoga saya paham.. trima kasih mas nur

**Comment by z4cky87** [comment]
nyerah juga mas... ada eror.. boleh minta dicontohin hehee... soalnya baru dasar banget saya 
![image](https://user-images.githubusercontent.com/8597550/127821584-a39b3b34-1b4c-4d13-9f10-64801d127cb4.png)
ini erornya

![image](https://user-images.githubusercontent.com/8597550/127821502-6a3079e8-082a-4ca3-a269-bf8af54b2da2.png)
ini cuplikan codingan

**Comment by ngekoding** [comment]
Silahkan cek kode terakhir mas, sudah saya tambahkan contohnya di branch master.

The commit 2b7756b

**Comment by z4cky87** [comment]
ok siap  mas nur

**Comment by z4cky87** [comment]
mas.. alhamdullilah berhasil .. makasih
