### ISSUE TITLE
error after scaning QrCode

### ISSUE THREAD

**Issue by HabibAlmaula** [ngekoding/whatsapp-api-tutorial#9]
saya mendapatkan error seperti ini mas @ngekoding setelah scan qrcode nya
![image](https://user-images.githubusercontent.com/39479500/100497478-64220400-318e-11eb-95c7-4ce54df3b292.png)

mungkin ada yang terlewatkan oleh saya mas? mohon solusinya

**Comment by ngekoding** [comment]
Silahkan gunakan versi library terakhir mas. Library secara berkala diupdate untuk menyesuaikan pembaruan WA.

**Comment by HabibAlmaula** [comment]
oke mas, ternyata memang libnya harus diupdate. 
terimakasih.
