### ISSUE TITLE
Otomatis mengambil pesan baru

### ISSUE THREAD

**Issue by rianwnoviantoro** [ngekoding/whatsapp-api-tutorial#93]
Saya ingin membuat fitur layaknya wa web ketika ada pesan baru pesan tersebut akan muncul di console, nah ketika saya mencoba memakai event message_recieved sesuai dokumentasi dan saya taruh didalam socket.io tidak terjadi apa". Bisa tolong dibantu kasih saya clue?

**Comment by ngekoding** [comment]
Maaf saya belum begitu paham apa yang dimaksud dan inginkan, bisa sertakan kode yang saat ini dibuat?
