### ISSUE TITLE
Error Starting 

### ISSUE THREAD

**Issue by BranGamer145** [ngekoding/whatsapp-api-tutorial#94]
Saya Menggunakan Bot Hosting Dan Kenapa Saat Saya Starting Menjadi Seperti Ini Tolong Dong Bantu saya ':(, Saya Sudah Mencoba Mengfix itu Tapi Masih Sama Saja.

Ini Fotonya:
![20210810081846](https://user-images.githubusercontent.com/74217443/128790695-e332f734-9585-4310-8198-e35d3a914f08.jpg)

**Comment by BranGamer145** [comment]
![Uploading 20210810081846.jpg…]()

**Comment by ngekoding** [comment]
Whatsapp-web.ja secara umum tidak bisa digunakan di shared hosting, karena tidak bisa menjalankan Puppeteer. Sehingga harus dipastikan bahwa hosting yang digunakan support untuk Node.js dan Puppeteer.

Silahkan ditanyakan ke penyedia hostingnya untuk informasi lebih jelasnya.

Solusinya, biasanya kita menggunakan VPS.

**Comment by BranGamer145** [comment]
> Whatsapp-web.ja secara umum tidak bisa digunakan di shared hosting, karena tidak bisa menjalankan Puppeteer. Sehingga harus dipastikan bahwa hosting yang digunakan support untuk Node.js dan Puppeteer.
> 
> Silahkan ditanyakan ke penyedia hostingnya untuk informasi lebih jelasnya.
> 
> Solusinya, biasanya kita menggunakan VPS.

Pakai Node.js Versi Berapa Kalau Mau Tau?

**Comment by ngekoding** [comment]
Bisa gunakan versi 14 atau yang lebih baru
