### ISSUE TITLE
Download Media(Images/Gif) To Sticker

### ISSUE THREAD

**Issue by Scoooolz** [ngekoding/whatsapp-api-tutorial#97]
Hallo, Aku pengen nanya,
Kalo misalnya ada yg mau send Media trus di reply (Bukan bot) dengan !sticker,
Gimana caranya biar bot nge download file trus di send ke sticker?

**Comment by ngekoding** [comment]
Sepertinya saya belum paham maksudnya.

**Comment by ngekoding** [comment]
No answer.
