### ISSUE TITLE
bagaimana jika mengirim pesan massal

### ISSUE THREAD

**Issue by ninegrafh** [ngekoding/whatsapp-api-tutorial#98]
bagaimana jika mengirim pesan massal,

**Comment by ngekoding** [comment]
Kalau dari sisi ketersediaan fungsi secara langsung dari library whatsapp-web.js belum ada, tapi bisa diakali dengan melakukan looping untuk setiap nomor yang akan dikirimkan.

**Comment by ninegrafh** [comment]
baik,mungkin ditunggu tutorialnya di yuotube pak,trimakasih

**Comment by ngekoding** [comment]
Looping adalah hal dasar.
